// Code generated by ent, DO NOT EDIT.

package consumer

import (
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldID, id))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldDeletedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldDeletedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldTenantID, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldEmail, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldNickname, v))
}

// Avatar applies equality check predicate on the "avatar" field. It's identical to AvatarEQ.
func Avatar(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldAvatar, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldPasswordHash, v))
}

// WechatOpenid applies equality check predicate on the "wechat_openid" field. It's identical to WechatOpenidEQ.
func WechatOpenid(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldWechatOpenid, v))
}

// WechatUnionid applies equality check predicate on the "wechat_unionid" field. It's identical to WechatUnionidEQ.
func WechatUnionid(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldWechatUnionid, v))
}

// RiskScore applies equality check predicate on the "risk_score" field. It's identical to RiskScoreEQ.
func RiskScore(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldRiskScore, v))
}

// LoginFailCount applies equality check predicate on the "login_fail_count" field. It's identical to LoginFailCountEQ.
func LoginFailCount(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLoginFailCount, v))
}

// LockedUntil applies equality check predicate on the "locked_until" field. It's identical to LockedUntilEQ.
func LockedUntil(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLockedUntil, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginIP applies equality check predicate on the "last_login_ip" field. It's identical to LastLoginIPEQ.
func LastLoginIP(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLastLoginIP, v))
}

// DeactivatedAt applies equality check predicate on the "deactivated_at" field. It's identical to DeactivatedAtEQ.
func DeactivatedAt(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldDeactivatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldDeletedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldDeletedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldTenantID))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldEmail, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameIsNil applies the IsNil predicate on the "nickname" field.
func NicknameIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldNickname))
}

// NicknameNotNil applies the NotNil predicate on the "nickname" field.
func NicknameNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldNickname))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldNickname, v))
}

// AvatarEQ applies the EQ predicate on the "avatar" field.
func AvatarEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldAvatar, v))
}

// AvatarNEQ applies the NEQ predicate on the "avatar" field.
func AvatarNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldAvatar, v))
}

// AvatarIn applies the In predicate on the "avatar" field.
func AvatarIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldAvatar, vs...))
}

// AvatarNotIn applies the NotIn predicate on the "avatar" field.
func AvatarNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldAvatar, vs...))
}

// AvatarGT applies the GT predicate on the "avatar" field.
func AvatarGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldAvatar, v))
}

// AvatarGTE applies the GTE predicate on the "avatar" field.
func AvatarGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldAvatar, v))
}

// AvatarLT applies the LT predicate on the "avatar" field.
func AvatarLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldAvatar, v))
}

// AvatarLTE applies the LTE predicate on the "avatar" field.
func AvatarLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldAvatar, v))
}

// AvatarContains applies the Contains predicate on the "avatar" field.
func AvatarContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldAvatar, v))
}

// AvatarHasPrefix applies the HasPrefix predicate on the "avatar" field.
func AvatarHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldAvatar, v))
}

// AvatarHasSuffix applies the HasSuffix predicate on the "avatar" field.
func AvatarHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldAvatar, v))
}

// AvatarIsNil applies the IsNil predicate on the "avatar" field.
func AvatarIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldAvatar))
}

// AvatarNotNil applies the NotNil predicate on the "avatar" field.
func AvatarNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldAvatar))
}

// AvatarEqualFold applies the EqualFold predicate on the "avatar" field.
func AvatarEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldAvatar, v))
}

// AvatarContainsFold applies the ContainsFold predicate on the "avatar" field.
func AvatarContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldAvatar, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldPasswordHash, v))
}

// WechatOpenidEQ applies the EQ predicate on the "wechat_openid" field.
func WechatOpenidEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldWechatOpenid, v))
}

// WechatOpenidNEQ applies the NEQ predicate on the "wechat_openid" field.
func WechatOpenidNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldWechatOpenid, v))
}

// WechatOpenidIn applies the In predicate on the "wechat_openid" field.
func WechatOpenidIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldWechatOpenid, vs...))
}

// WechatOpenidNotIn applies the NotIn predicate on the "wechat_openid" field.
func WechatOpenidNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldWechatOpenid, vs...))
}

// WechatOpenidGT applies the GT predicate on the "wechat_openid" field.
func WechatOpenidGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldWechatOpenid, v))
}

// WechatOpenidGTE applies the GTE predicate on the "wechat_openid" field.
func WechatOpenidGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldWechatOpenid, v))
}

// WechatOpenidLT applies the LT predicate on the "wechat_openid" field.
func WechatOpenidLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldWechatOpenid, v))
}

// WechatOpenidLTE applies the LTE predicate on the "wechat_openid" field.
func WechatOpenidLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldWechatOpenid, v))
}

// WechatOpenidContains applies the Contains predicate on the "wechat_openid" field.
func WechatOpenidContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldWechatOpenid, v))
}

// WechatOpenidHasPrefix applies the HasPrefix predicate on the "wechat_openid" field.
func WechatOpenidHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldWechatOpenid, v))
}

// WechatOpenidHasSuffix applies the HasSuffix predicate on the "wechat_openid" field.
func WechatOpenidHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldWechatOpenid, v))
}

// WechatOpenidIsNil applies the IsNil predicate on the "wechat_openid" field.
func WechatOpenidIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldWechatOpenid))
}

// WechatOpenidNotNil applies the NotNil predicate on the "wechat_openid" field.
func WechatOpenidNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldWechatOpenid))
}

// WechatOpenidEqualFold applies the EqualFold predicate on the "wechat_openid" field.
func WechatOpenidEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldWechatOpenid, v))
}

// WechatOpenidContainsFold applies the ContainsFold predicate on the "wechat_openid" field.
func WechatOpenidContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldWechatOpenid, v))
}

// WechatUnionidEQ applies the EQ predicate on the "wechat_unionid" field.
func WechatUnionidEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldWechatUnionid, v))
}

// WechatUnionidNEQ applies the NEQ predicate on the "wechat_unionid" field.
func WechatUnionidNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldWechatUnionid, v))
}

// WechatUnionidIn applies the In predicate on the "wechat_unionid" field.
func WechatUnionidIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldWechatUnionid, vs...))
}

// WechatUnionidNotIn applies the NotIn predicate on the "wechat_unionid" field.
func WechatUnionidNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldWechatUnionid, vs...))
}

// WechatUnionidGT applies the GT predicate on the "wechat_unionid" field.
func WechatUnionidGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldWechatUnionid, v))
}

// WechatUnionidGTE applies the GTE predicate on the "wechat_unionid" field.
func WechatUnionidGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldWechatUnionid, v))
}

// WechatUnionidLT applies the LT predicate on the "wechat_unionid" field.
func WechatUnionidLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldWechatUnionid, v))
}

// WechatUnionidLTE applies the LTE predicate on the "wechat_unionid" field.
func WechatUnionidLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldWechatUnionid, v))
}

// WechatUnionidContains applies the Contains predicate on the "wechat_unionid" field.
func WechatUnionidContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldWechatUnionid, v))
}

// WechatUnionidHasPrefix applies the HasPrefix predicate on the "wechat_unionid" field.
func WechatUnionidHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldWechatUnionid, v))
}

// WechatUnionidHasSuffix applies the HasSuffix predicate on the "wechat_unionid" field.
func WechatUnionidHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldWechatUnionid, v))
}

// WechatUnionidIsNil applies the IsNil predicate on the "wechat_unionid" field.
func WechatUnionidIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldWechatUnionid))
}

// WechatUnionidNotNil applies the NotNil predicate on the "wechat_unionid" field.
func WechatUnionidNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldWechatUnionid))
}

// WechatUnionidEqualFold applies the EqualFold predicate on the "wechat_unionid" field.
func WechatUnionidEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldWechatUnionid, v))
}

// WechatUnionidContainsFold applies the ContainsFold predicate on the "wechat_unionid" field.
func WechatUnionidContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldWechatUnionid, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldStatus, vs...))
}

// RiskScoreEQ applies the EQ predicate on the "risk_score" field.
func RiskScoreEQ(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldRiskScore, v))
}

// RiskScoreNEQ applies the NEQ predicate on the "risk_score" field.
func RiskScoreNEQ(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldRiskScore, v))
}

// RiskScoreIn applies the In predicate on the "risk_score" field.
func RiskScoreIn(vs ...int) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldRiskScore, vs...))
}

// RiskScoreNotIn applies the NotIn predicate on the "risk_score" field.
func RiskScoreNotIn(vs ...int) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldRiskScore, vs...))
}

// RiskScoreGT applies the GT predicate on the "risk_score" field.
func RiskScoreGT(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldRiskScore, v))
}

// RiskScoreGTE applies the GTE predicate on the "risk_score" field.
func RiskScoreGTE(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldRiskScore, v))
}

// RiskScoreLT applies the LT predicate on the "risk_score" field.
func RiskScoreLT(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldRiskScore, v))
}

// RiskScoreLTE applies the LTE predicate on the "risk_score" field.
func RiskScoreLTE(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldRiskScore, v))
}

// LoginFailCountEQ applies the EQ predicate on the "login_fail_count" field.
func LoginFailCountEQ(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLoginFailCount, v))
}

// LoginFailCountNEQ applies the NEQ predicate on the "login_fail_count" field.
func LoginFailCountNEQ(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldLoginFailCount, v))
}

// LoginFailCountIn applies the In predicate on the "login_fail_count" field.
func LoginFailCountIn(vs ...int) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldLoginFailCount, vs...))
}

// LoginFailCountNotIn applies the NotIn predicate on the "login_fail_count" field.
func LoginFailCountNotIn(vs ...int) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldLoginFailCount, vs...))
}

// LoginFailCountGT applies the GT predicate on the "login_fail_count" field.
func LoginFailCountGT(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldLoginFailCount, v))
}

// LoginFailCountGTE applies the GTE predicate on the "login_fail_count" field.
func LoginFailCountGTE(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldLoginFailCount, v))
}

// LoginFailCountLT applies the LT predicate on the "login_fail_count" field.
func LoginFailCountLT(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldLoginFailCount, v))
}

// LoginFailCountLTE applies the LTE predicate on the "login_fail_count" field.
func LoginFailCountLTE(v int) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldLoginFailCount, v))
}

// LockedUntilEQ applies the EQ predicate on the "locked_until" field.
func LockedUntilEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLockedUntil, v))
}

// LockedUntilNEQ applies the NEQ predicate on the "locked_until" field.
func LockedUntilNEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldLockedUntil, v))
}

// LockedUntilIn applies the In predicate on the "locked_until" field.
func LockedUntilIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldLockedUntil, vs...))
}

// LockedUntilNotIn applies the NotIn predicate on the "locked_until" field.
func LockedUntilNotIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldLockedUntil, vs...))
}

// LockedUntilGT applies the GT predicate on the "locked_until" field.
func LockedUntilGT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldLockedUntil, v))
}

// LockedUntilGTE applies the GTE predicate on the "locked_until" field.
func LockedUntilGTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldLockedUntil, v))
}

// LockedUntilLT applies the LT predicate on the "locked_until" field.
func LockedUntilLT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldLockedUntil, v))
}

// LockedUntilLTE applies the LTE predicate on the "locked_until" field.
func LockedUntilLTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldLockedUntil, v))
}

// LockedUntilIsNil applies the IsNil predicate on the "locked_until" field.
func LockedUntilIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldLockedUntil))
}

// LockedUntilNotNil applies the NotNil predicate on the "locked_until" field.
func LockedUntilNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldLockedUntil))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldLastLoginAt))
}

// LastLoginIPEQ applies the EQ predicate on the "last_login_ip" field.
func LastLoginIPEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldLastLoginIP, v))
}

// LastLoginIPNEQ applies the NEQ predicate on the "last_login_ip" field.
func LastLoginIPNEQ(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldLastLoginIP, v))
}

// LastLoginIPIn applies the In predicate on the "last_login_ip" field.
func LastLoginIPIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldLastLoginIP, vs...))
}

// LastLoginIPNotIn applies the NotIn predicate on the "last_login_ip" field.
func LastLoginIPNotIn(vs ...string) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldLastLoginIP, vs...))
}

// LastLoginIPGT applies the GT predicate on the "last_login_ip" field.
func LastLoginIPGT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldLastLoginIP, v))
}

// LastLoginIPGTE applies the GTE predicate on the "last_login_ip" field.
func LastLoginIPGTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldLastLoginIP, v))
}

// LastLoginIPLT applies the LT predicate on the "last_login_ip" field.
func LastLoginIPLT(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldLastLoginIP, v))
}

// LastLoginIPLTE applies the LTE predicate on the "last_login_ip" field.
func LastLoginIPLTE(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldLastLoginIP, v))
}

// LastLoginIPContains applies the Contains predicate on the "last_login_ip" field.
func LastLoginIPContains(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContains(FieldLastLoginIP, v))
}

// LastLoginIPHasPrefix applies the HasPrefix predicate on the "last_login_ip" field.
func LastLoginIPHasPrefix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasPrefix(FieldLastLoginIP, v))
}

// LastLoginIPHasSuffix applies the HasSuffix predicate on the "last_login_ip" field.
func LastLoginIPHasSuffix(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldHasSuffix(FieldLastLoginIP, v))
}

// LastLoginIPIsNil applies the IsNil predicate on the "last_login_ip" field.
func LastLoginIPIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldLastLoginIP))
}

// LastLoginIPNotNil applies the NotNil predicate on the "last_login_ip" field.
func LastLoginIPNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldLastLoginIP))
}

// LastLoginIPEqualFold applies the EqualFold predicate on the "last_login_ip" field.
func LastLoginIPEqualFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldEqualFold(FieldLastLoginIP, v))
}

// LastLoginIPContainsFold applies the ContainsFold predicate on the "last_login_ip" field.
func LastLoginIPContainsFold(v string) predicate.Consumer {
	return predicate.Consumer(sql.FieldContainsFold(FieldLastLoginIP, v))
}

// DeactivatedAtEQ applies the EQ predicate on the "deactivated_at" field.
func DeactivatedAtEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldEQ(FieldDeactivatedAt, v))
}

// DeactivatedAtNEQ applies the NEQ predicate on the "deactivated_at" field.
func DeactivatedAtNEQ(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNEQ(FieldDeactivatedAt, v))
}

// DeactivatedAtIn applies the In predicate on the "deactivated_at" field.
func DeactivatedAtIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldIn(FieldDeactivatedAt, vs...))
}

// DeactivatedAtNotIn applies the NotIn predicate on the "deactivated_at" field.
func DeactivatedAtNotIn(vs ...time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldNotIn(FieldDeactivatedAt, vs...))
}

// DeactivatedAtGT applies the GT predicate on the "deactivated_at" field.
func DeactivatedAtGT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGT(FieldDeactivatedAt, v))
}

// DeactivatedAtGTE applies the GTE predicate on the "deactivated_at" field.
func DeactivatedAtGTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldGTE(FieldDeactivatedAt, v))
}

// DeactivatedAtLT applies the LT predicate on the "deactivated_at" field.
func DeactivatedAtLT(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLT(FieldDeactivatedAt, v))
}

// DeactivatedAtLTE applies the LTE predicate on the "deactivated_at" field.
func DeactivatedAtLTE(v time.Time) predicate.Consumer {
	return predicate.Consumer(sql.FieldLTE(FieldDeactivatedAt, v))
}

// DeactivatedAtIsNil applies the IsNil predicate on the "deactivated_at" field.
func DeactivatedAtIsNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldIsNull(FieldDeactivatedAt))
}

// DeactivatedAtNotNil applies the NotNil predicate on the "deactivated_at" field.
func DeactivatedAtNotNil() predicate.Consumer {
	return predicate.Consumer(sql.FieldNotNull(FieldDeactivatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Consumer) predicate.Consumer {
	return predicate.Consumer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Consumer) predicate.Consumer {
	return predicate.Consumer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Consumer) predicate.Consumer {
	return predicate.Consumer(sql.NotPredicates(p))
}
