// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-admin/app/consumer/service/internal/data"
	"go-wind-admin/app/consumer/service/internal/server"
	"go-wind-admin/app/consumer/service/internal/service"
	"go-wind-admin/pkg/jwt"
)

// Injectors from wire.go:

// initApp 初始化 kratos 应用的 Wire provider 入口。
// initApp initializes the Wire provider entry for the kratos application.
//
// 参数 / Parameters:
//   - *bootstrap.Context: 引导上下文 / *bootstrap.Context: bootstrap context
//
// 返回 / Returns:
//   - *kratos.App: 已构建的应用实例 / *kratos.App: constructed application instance
//   - func(): 应用关闭时的清理函数 / func(): cleanup function to run on shutdown
//   - error: 构建过程中可能发生的错误 / error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	// JWT Helper
	jwtHelper := jwt.NewJWTHelper(context)

	// Event Bus
	eventBus := NewEventBus(context)

	// SMS Clients
	smsClients, err := NewSMSClients(context)
	if err != nil {
		return nil, nil, err
	}

	// Payment Client
	paymentClient, err := NewPaymentClient(context)
	if err != nil {
		return nil, nil, err
	}

	// Redis Client
	client, cleanup, err := NewRedisClient(context)
	if err != nil {
		return nil, nil, err
	}

	// Ent Client
	entClient, cleanup2, err := NewEntClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	// Logistics Client
	logisticsClient, err := NewLogisticsClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	// Data Layer - Repositories
	consumerRepo := data.NewConsumerRepo(context, entClient)
	loginLogRepo := data.NewLoginLogRepo(context, entClient)
	smsLogRepo := data.NewSMSLogRepo(context, entClient)
	paymentOrderRepo := data.NewPaymentOrderRepo(context, entClient)
	financeAccountRepo := data.NewFinanceAccountRepo(context, entClient)
	financeTransactionRepo := data.NewFinanceTransactionRepo(context, entClient)
	logisticsTrackingRepo := data.NewLogisticsTrackingRepo(context, entClient)

	// Service Layer
	consumerService := service.NewConsumerService(context, consumerRepo, loginLogRepo, eventBus, jwtHelper)
	smsService := service.NewSMSService(context, smsLogRepo, client, smsClients)
	paymentService := service.NewPaymentService(context, paymentOrderRepo, paymentClient, eventBus)
	financeService := service.NewFinanceService(context, financeAccountRepo, financeTransactionRepo, eventBus)
	wechatService := service.NewWechatService(context, client, eventBus)
	logisticsService := service.NewLogisticsService(context, logisticsTrackingRepo, logisticsClient, client, eventBus)

	// Server Layer
	httpServer, err := server.NewRestServer(context, consumerService, smsService, paymentService, financeService, wechatService, logisticsService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	kafkaServer, err := server.NewKafkaServer(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	// Create App
	app := newApp(context, httpServer, kafkaServer)

	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
