// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-admin/app/consumer/service/internal/data"
	"go-wind-admin/app/consumer/service/internal/server"
	"go-wind-admin/app/consumer/service/internal/service"
)

// Injectors from wire.go:

// initApp 初始化 kratos 应用的 Wire provider 入口。
// initApp initializes the Wire provider entry for the kratos application.
//
// 参数 / Parameters:
//   - *bootstrap.Context: 引导上下文 / *bootstrap.Context: bootstrap context
//
// 返回 / Returns:
//   - *kratos.App: 已构建的应用实例 / *kratos.App: constructed application instance
//   - func(): 应用关闭时的清理函数 / func(): cleanup function to run on shutdown
//   - error: 构建过程中可能发生的错误 / error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	// Data layer
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	
	redisClient, cleanup2, err := data.NewRedisClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	
	kafkaClient, cleanup3, err := data.NewKafkaClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	
	// Repositories
	consumerRepo := data.NewConsumerRepo(context, entClient)
	loginLogRepo := data.NewLoginLogRepo(context, entClient)
	smsLogRepo := data.NewSMSLogRepo(context, entClient)
	paymentOrderRepo := data.NewPaymentOrderRepo(context, entClient)
	financeAccountRepo := data.NewFinanceAccountRepo(context, entClient)
	financeTransactionRepo := data.NewFinanceTransactionRepo(context, entClient)
	mediaFileRepo := data.NewMediaFileRepo(context, entClient)
	logisticsTrackingRepo := data.NewLogisticsTrackingRepo(context, entClient)
	freightTemplateRepo := data.NewFreightTemplateRepo(context, entClient)
	tenantConfigRepo := data.NewTenantConfigRepo(context, entClient)
	
	// External clients
	smsClient := data.NewSMSClient(context)
	paymentClient := data.NewPaymentClient(context)
	ossClient := data.NewOSSClient(context)
	logisticsClient := data.NewLogisticsClient(context)
	wechatClient := data.NewWechatClient(context)
	
	// Services
	consumerService := service.NewConsumerService(context, consumerRepo, loginLogRepo, smsClient, wechatClient, kafkaClient)
	smsService := service.NewSMSService(context, smsLogRepo, smsClient, redisClient)
	paymentService := service.NewPaymentService(context, paymentOrderRepo, paymentClient, kafkaClient)
	financeService := service.NewFinanceService(context, financeAccountRepo, financeTransactionRepo, paymentService, kafkaClient)
	wechatService := service.NewWechatService(context, wechatClient, redisClient, kafkaClient)
	mediaService := service.NewMediaService(context, mediaFileRepo, ossClient)
	logisticsService := service.NewLogisticsService(context, logisticsTrackingRepo, logisticsClient, redisClient, kafkaClient)
	freightService := service.NewFreightService(context, freightTemplateRepo)
	tenantConfigService := service.NewTenantConfigService(context, tenantConfigRepo, redisClient)
	
	// Servers
	httpServer, err := server.NewHTTPServer(
		context,
		consumerService,
		smsService,
		paymentService,
		financeService,
		wechatService,
		mediaService,
		logisticsService,
		freightService,
		tenantConfigService,
	)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	
	kafkaServer, err := server.NewKafkaServer(context, financeService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	
	app := newApp(context, httpServer, kafkaServer)
	
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
