// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConsumerUsersColumns holds the columns for the "consumer_users" table.
	ConsumerUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "phone", Type: field.TypeString, Size: 20, Comment: "手机号"},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 100, Comment: "邮箱"},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Size: 50, Comment: "昵称"},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Size: 500, Comment: "头像URL"},
		{Name: "password_hash", Type: field.TypeString, Size: 255, Comment: "密码哈希"},
		{Name: "wechat_openid", Type: field.TypeString, Nullable: true, Size: 100, Comment: "微信OpenID"},
		{Name: "wechat_unionid", Type: field.TypeString, Nullable: true, Size: 100, Comment: "微信UnionID"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态", Enums: []string{"NORMAL", "LOCKED", "DEACTIVATED"}, Default: "NORMAL"},
		{Name: "risk_score", Type: field.TypeInt, Comment: "风险评分 0-100", Default: 0},
		{Name: "login_fail_count", Type: field.TypeInt, Comment: "登录失败次数", Default: 0},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true, Comment: "锁定截止时间"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, Comment: "最后登录时间"},
		{Name: "last_login_ip", Type: field.TypeString, Nullable: true, Size: 50, Comment: "最后登录IP"},
		{Name: "deactivated_at", Type: field.TypeTime, Nullable: true, Comment: "注销时间"},
	}
	// ConsumerUsersTable holds the schema information for the "consumer_users" table.
	ConsumerUsersTable = &schema.Table{
		Name:       "consumer_users",
		Comment:    "C端用户表",
		Columns:    ConsumerUsersColumns,
		PrimaryKey: []*schema.Column{ConsumerUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_consumer_tenant_phone",
				Unique:  true,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[8]},
			},
			{
				Name:    "idx_consumer_tenant_email",
				Unique:  true,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[9]},
			},
			{
				Name:    "idx_consumer_tenant_wechat_openid",
				Unique:  false,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[13]},
			},
			{
				Name:    "idx_consumer_tenant_wechat_unionid",
				Unique:  false,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[14]},
			},
			{
				Name:    "idx_consumer_tenant_status",
				Unique:  false,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[15]},
			},
			{
				Name:    "idx_consumer_tenant_last_login_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[19]},
			},
			{
				Name:    "idx_consumer_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerUsersColumns[7], ConsumerUsersColumns[4]},
			},
		},
	}
	// ConsumerFinanceAccountsColumns holds the columns for the "consumer_finance_accounts" table.
	ConsumerFinanceAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "consumer_id", Type: field.TypeUint32, Comment: "用户ID"},
		{Name: "balance", Type: field.TypeString, Size: 20, Comment: "账户余额（decimal字符串）", Default: "0"},
		{Name: "frozen_balance", Type: field.TypeString, Size: 20, Comment: "冻结余额（decimal字符串）", Default: "0"},
	}
	// ConsumerFinanceAccountsTable holds the schema information for the "consumer_finance_accounts" table.
	ConsumerFinanceAccountsTable = &schema.Table{
		Name:       "consumer_finance_accounts",
		Comment:    "财务账户表",
		Columns:    ConsumerFinanceAccountsColumns,
		PrimaryKey: []*schema.Column{ConsumerFinanceAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_finance_account_tenant_consumer",
				Unique:  true,
				Columns: []*schema.Column{ConsumerFinanceAccountsColumns[4], ConsumerFinanceAccountsColumns[5]},
			},
		},
	}
	// ConsumerFinanceTransactionsColumns holds the columns for the "consumer_finance_transactions" table.
	ConsumerFinanceTransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "consumer_id", Type: field.TypeUint32, Comment: "用户ID"},
		{Name: "transaction_no", Type: field.TypeString, Size: 64, Comment: "流水号"},
		{Name: "transaction_type", Type: field.TypeEnum, Comment: "交易类型", Enums: []string{"RECHARGE", "CONSUME", "WITHDRAW", "REFUND"}},
		{Name: "amount", Type: field.TypeString, Size: 20, Comment: "交易金额（decimal字符串）"},
		{Name: "balance_before", Type: field.TypeString, Size: 20, Comment: "交易前余额（decimal字符串）"},
		{Name: "balance_after", Type: field.TypeString, Size: 20, Comment: "交易后余额（decimal字符串）"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200, Comment: "交易描述"},
		{Name: "related_order_no", Type: field.TypeString, Nullable: true, Size: 64, Comment: "关联订单号"},
		{Name: "operator_id", Type: field.TypeUint32, Nullable: true, Comment: "操作人ID"},
	}
	// ConsumerFinanceTransactionsTable holds the schema information for the "consumer_finance_transactions" table.
	ConsumerFinanceTransactionsTable = &schema.Table{
		Name:       "consumer_finance_transactions",
		Comment:    "财务流水表",
		Columns:    ConsumerFinanceTransactionsColumns,
		PrimaryKey: []*schema.Column{ConsumerFinanceTransactionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_finance_transaction_transaction_no",
				Unique:  true,
				Columns: []*schema.Column{ConsumerFinanceTransactionsColumns[4]},
			},
			{
				Name:    "idx_finance_transaction_tenant_consumer_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFinanceTransactionsColumns[2], ConsumerFinanceTransactionsColumns[3], ConsumerFinanceTransactionsColumns[1]},
			},
			{
				Name:    "idx_finance_transaction_tenant_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFinanceTransactionsColumns[2], ConsumerFinanceTransactionsColumns[5], ConsumerFinanceTransactionsColumns[1]},
			},
			{
				Name:    "idx_finance_transaction_related_order_no",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFinanceTransactionsColumns[10]},
			},
			{
				Name:    "idx_finance_transaction_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFinanceTransactionsColumns[2], ConsumerFinanceTransactionsColumns[1]},
			},
		},
	}
	// ConsumerFreightTemplatesColumns holds the columns for the "consumer_freight_templates" table.
	ConsumerFreightTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 100, Comment: "模板名称"},
		{Name: "calculation_type", Type: field.TypeEnum, Comment: "计算方式", Enums: []string{"BY_WEIGHT", "BY_DISTANCE"}},
		{Name: "first_weight", Type: field.TypeString, Nullable: true, Size: 20, Comment: "首重（kg）"},
		{Name: "first_price", Type: field.TypeString, Nullable: true, Size: 20, Comment: "首重价格（decimal字符串）"},
		{Name: "additional_weight", Type: field.TypeString, Nullable: true, Size: 20, Comment: "续重（kg）"},
		{Name: "additional_price", Type: field.TypeString, Nullable: true, Size: 20, Comment: "续重价格（decimal字符串）"},
		{Name: "region_rules", Type: field.TypeJSON, Nullable: true, Comment: "地区规则"},
		{Name: "free_shipping_rules", Type: field.TypeJSON, Nullable: true, Comment: "包邮规则"},
		{Name: "is_active", Type: field.TypeBool, Comment: "是否启用", Default: true},
	}
	// ConsumerFreightTemplatesTable holds the schema information for the "consumer_freight_templates" table.
	ConsumerFreightTemplatesTable = &schema.Table{
		Name:       "consumer_freight_templates",
		Comment:    "运费模板表",
		Columns:    ConsumerFreightTemplatesColumns,
		PrimaryKey: []*schema.Column{ConsumerFreightTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_freight_template_tenant_is_active",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFreightTemplatesColumns[7], ConsumerFreightTemplatesColumns[16]},
			},
			{
				Name:    "idx_freight_template_tenant_calculation_type",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFreightTemplatesColumns[7], ConsumerFreightTemplatesColumns[9]},
			},
			{
				Name:    "idx_freight_template_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerFreightTemplatesColumns[7], ConsumerFreightTemplatesColumns[4]},
			},
		},
	}
	// ConsumerLoginLogsColumns holds the columns for the "consumer_login_logs" table.
	ConsumerLoginLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "consumer_id", Type: field.TypeUint32, Comment: "用户ID"},
		{Name: "phone", Type: field.TypeString, Size: 20, Comment: "手机号"},
		{Name: "login_type", Type: field.TypeEnum, Comment: "登录方式", Enums: []string{"PHONE", "WECHAT"}},
		{Name: "success", Type: field.TypeBool, Comment: "是否成功", Default: false},
		{Name: "fail_reason", Type: field.TypeString, Nullable: true, Size: 200, Comment: "失败原因"},
		{Name: "ip_address", Type: field.TypeString, Size: 50, Comment: "IP地址"},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 500, Comment: "User Agent"},
		{Name: "device_type", Type: field.TypeString, Nullable: true, Size: 50, Comment: "设备类型"},
		{Name: "login_at", Type: field.TypeTime, Comment: "登录时间"},
	}
	// ConsumerLoginLogsTable holds the schema information for the "consumer_login_logs" table.
	ConsumerLoginLogsTable = &schema.Table{
		Name:       "consumer_login_logs",
		Comment:    "C端用户登录日志表",
		Columns:    ConsumerLoginLogsColumns,
		PrimaryKey: []*schema.Column{ConsumerLoginLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_login_log_tenant_consumer_login_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLoginLogsColumns[1], ConsumerLoginLogsColumns[2], ConsumerLoginLogsColumns[10]},
			},
			{
				Name:    "idx_login_log_tenant_phone_login_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLoginLogsColumns[1], ConsumerLoginLogsColumns[3], ConsumerLoginLogsColumns[10]},
			},
			{
				Name:    "idx_login_log_tenant_login_type",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLoginLogsColumns[1], ConsumerLoginLogsColumns[4]},
			},
			{
				Name:    "idx_login_log_tenant_success",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLoginLogsColumns[1], ConsumerLoginLogsColumns[5]},
			},
			{
				Name:    "idx_login_log_tenant_ip_address",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLoginLogsColumns[1], ConsumerLoginLogsColumns[7]},
			},
			{
				Name:    "idx_login_log_tenant_login_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLoginLogsColumns[1], ConsumerLoginLogsColumns[10]},
			},
		},
	}
	// ConsumerLogisticsTrackingsColumns holds the columns for the "consumer_logistics_trackings" table.
	ConsumerLogisticsTrackingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "tracking_no", Type: field.TypeString, Size: 100, Comment: "运单号"},
		{Name: "courier_company", Type: field.TypeString, Size: 50, Comment: "快递公司"},
		{Name: "status", Type: field.TypeEnum, Comment: "物流状态", Enums: []string{"PENDING", "IN_TRANSIT", "DELIVERING", "DELIVERED"}, Default: "PENDING"},
		{Name: "tracking_info", Type: field.TypeJSON, Comment: "物流轨迹"},
		{Name: "last_updated_at", Type: field.TypeTime, Comment: "最后更新时间"},
	}
	// ConsumerLogisticsTrackingsTable holds the schema information for the "consumer_logistics_trackings" table.
	ConsumerLogisticsTrackingsTable = &schema.Table{
		Name:       "consumer_logistics_trackings",
		Comment:    "物流跟踪表",
		Columns:    ConsumerLogisticsTrackingsColumns,
		PrimaryKey: []*schema.Column{ConsumerLogisticsTrackingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_logistics_tracking_tenant_tracking_no",
				Unique:  true,
				Columns: []*schema.Column{ConsumerLogisticsTrackingsColumns[2], ConsumerLogisticsTrackingsColumns[3]},
			},
			{
				Name:    "idx_logistics_tracking_tenant_status",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLogisticsTrackingsColumns[2], ConsumerLogisticsTrackingsColumns[5]},
			},
			{
				Name:    "idx_logistics_tracking_tenant_courier_company",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLogisticsTrackingsColumns[2], ConsumerLogisticsTrackingsColumns[4]},
			},
			{
				Name:    "idx_logistics_tracking_tenant_last_updated_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLogisticsTrackingsColumns[2], ConsumerLogisticsTrackingsColumns[7]},
			},
			{
				Name:    "idx_logistics_tracking_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerLogisticsTrackingsColumns[2], ConsumerLogisticsTrackingsColumns[1]},
			},
		},
	}
	// ConsumerMediaFilesColumns holds the columns for the "consumer_media_files" table.
	ConsumerMediaFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "consumer_id", Type: field.TypeUint32, Comment: "上传者ID"},
		{Name: "file_name", Type: field.TypeString, Size: 255, Comment: "文件名"},
		{Name: "file_type", Type: field.TypeEnum, Comment: "文件类型", Enums: []string{"IMAGE", "VIDEO"}},
		{Name: "file_format", Type: field.TypeString, Size: 20, Comment: "文件格式"},
		{Name: "file_size", Type: field.TypeUint64, Comment: "文件大小（字节）"},
		{Name: "file_url", Type: field.TypeString, Size: 500, Comment: "文件URL"},
		{Name: "thumbnail_url", Type: field.TypeString, Nullable: true, Size: 500, Comment: "缩略图URL"},
		{Name: "oss_bucket", Type: field.TypeString, Size: 100, Comment: "OSS Bucket"},
		{Name: "oss_key", Type: field.TypeString, Size: 500, Comment: "OSS Key"},
		{Name: "is_deleted", Type: field.TypeBool, Comment: "是否删除", Default: false},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
	}
	// ConsumerMediaFilesTable holds the schema information for the "consumer_media_files" table.
	ConsumerMediaFilesTable = &schema.Table{
		Name:       "consumer_media_files",
		Comment:    "媒体文件表",
		Columns:    ConsumerMediaFilesColumns,
		PrimaryKey: []*schema.Column{ConsumerMediaFilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_media_file_tenant_consumer_is_deleted",
				Unique:  false,
				Columns: []*schema.Column{ConsumerMediaFilesColumns[2], ConsumerMediaFilesColumns[3], ConsumerMediaFilesColumns[12]},
			},
			{
				Name:    "idx_media_file_tenant_file_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerMediaFilesColumns[2], ConsumerMediaFilesColumns[5], ConsumerMediaFilesColumns[1]},
			},
			{
				Name:    "idx_media_file_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerMediaFilesColumns[2], ConsumerMediaFilesColumns[1]},
			},
			{
				Name:    "idx_media_file_oss_key",
				Unique:  false,
				Columns: []*schema.Column{ConsumerMediaFilesColumns[11]},
			},
		},
	}
	// ConsumerPaymentOrdersColumns holds the columns for the "consumer_payment_orders" table.
	ConsumerPaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "order_no", Type: field.TypeString, Size: 64, Comment: "订单号"},
		{Name: "consumer_id", Type: field.TypeUint32, Comment: "用户ID"},
		{Name: "payment_method", Type: field.TypeEnum, Comment: "支付方式", Enums: []string{"WECHAT", "ALIPAY", "YEEPAY"}},
		{Name: "payment_type", Type: field.TypeEnum, Comment: "支付类型", Enums: []string{"APP", "H5", "MINI", "QRCODE"}},
		{Name: "amount", Type: field.TypeString, Size: 20, Comment: "支付金额（decimal字符串）"},
		{Name: "status", Type: field.TypeEnum, Comment: "订单状态", Enums: []string{"PENDING", "SUCCESS", "FAILED", "CLOSED", "REFUNDED"}, Default: "PENDING"},
		{Name: "transaction_id", Type: field.TypeString, Nullable: true, Size: 100, Comment: "第三方交易号"},
		{Name: "callback_data", Type: field.TypeString, Nullable: true, Size: 2000, Comment: "回调数据"},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true, Comment: "支付时间"},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true, Comment: "关闭时间"},
		{Name: "expires_at", Type: field.TypeTime, Comment: "过期时间"},
	}
	// ConsumerPaymentOrdersTable holds the schema information for the "consumer_payment_orders" table.
	ConsumerPaymentOrdersTable = &schema.Table{
		Name:       "consumer_payment_orders",
		Comment:    "支付订单表",
		Columns:    ConsumerPaymentOrdersColumns,
		PrimaryKey: []*schema.Column{ConsumerPaymentOrdersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_payment_order_tenant_order_no",
				Unique:  true,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[4], ConsumerPaymentOrdersColumns[5]},
			},
			{
				Name:    "idx_payment_order_tenant_consumer_status",
				Unique:  false,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[4], ConsumerPaymentOrdersColumns[6], ConsumerPaymentOrdersColumns[10]},
			},
			{
				Name:    "idx_payment_order_transaction_id",
				Unique:  false,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[11]},
			},
			{
				Name:    "idx_payment_order_tenant_payment_method",
				Unique:  false,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[4], ConsumerPaymentOrdersColumns[7]},
			},
			{
				Name:    "idx_payment_order_tenant_status",
				Unique:  false,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[4], ConsumerPaymentOrdersColumns[10]},
			},
			{
				Name:    "idx_payment_order_tenant_expires_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[4], ConsumerPaymentOrdersColumns[15]},
			},
			{
				Name:    "idx_payment_order_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerPaymentOrdersColumns[4], ConsumerPaymentOrdersColumns[1]},
			},
		},
	}
	// ConsumerSmsLogsColumns holds the columns for the "consumer_sms_logs" table.
	ConsumerSmsLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "phone", Type: field.TypeString, Size: 20, Comment: "手机号"},
		{Name: "sms_type", Type: field.TypeEnum, Comment: "短信类型", Enums: []string{"VERIFICATION", "NOTIFICATION"}},
		{Name: "content", Type: field.TypeString, Size: 500, Comment: "短信内容"},
		{Name: "code", Type: field.TypeString, Nullable: true, Size: 10, Comment: "验证码"},
		{Name: "channel", Type: field.TypeEnum, Comment: "短信通道", Enums: []string{"ALIYUN", "TENCENT"}},
		{Name: "status", Type: field.TypeEnum, Comment: "发送状态", Enums: []string{"PENDING", "SUCCESS", "FAILED"}, Default: "PENDING"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 200, Comment: "错误信息"},
		{Name: "sent_at", Type: field.TypeTime, Comment: "发送时间"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, Comment: "过期时间"},
	}
	// ConsumerSmsLogsTable holds the schema information for the "consumer_sms_logs" table.
	ConsumerSmsLogsTable = &schema.Table{
		Name:       "consumer_sms_logs",
		Comment:    "短信日志表",
		Columns:    ConsumerSmsLogsColumns,
		PrimaryKey: []*schema.Column{ConsumerSmsLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_sms_log_tenant_phone_sent_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerSmsLogsColumns[1], ConsumerSmsLogsColumns[2], ConsumerSmsLogsColumns[9]},
			},
			{
				Name:    "idx_sms_log_tenant_sms_type_status",
				Unique:  false,
				Columns: []*schema.Column{ConsumerSmsLogsColumns[1], ConsumerSmsLogsColumns[3], ConsumerSmsLogsColumns[7]},
			},
			{
				Name:    "idx_sms_log_tenant_channel",
				Unique:  false,
				Columns: []*schema.Column{ConsumerSmsLogsColumns[1], ConsumerSmsLogsColumns[6]},
			},
			{
				Name:    "idx_sms_log_tenant_sent_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerSmsLogsColumns[1], ConsumerSmsLogsColumns[9]},
			},
			{
				Name:    "idx_sms_log_tenant_expires_at",
				Unique:  false,
				Columns: []*schema.Column{ConsumerSmsLogsColumns[1], ConsumerSmsLogsColumns[10]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConsumerUsersTable,
		ConsumerFinanceAccountsTable,
		ConsumerFinanceTransactionsTable,
		ConsumerFreightTemplatesTable,
		ConsumerLoginLogsTable,
		ConsumerLogisticsTrackingsTable,
		ConsumerMediaFilesTable,
		ConsumerPaymentOrdersTable,
		ConsumerSmsLogsTable,
	}
)

func init() {
	ConsumerUsersTable.Annotation = &entsql.Annotation{
		Table:     "consumer_users",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerFinanceAccountsTable.Annotation = &entsql.Annotation{
		Table:     "consumer_finance_accounts",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerFinanceTransactionsTable.Annotation = &entsql.Annotation{
		Table:     "consumer_finance_transactions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerFreightTemplatesTable.Annotation = &entsql.Annotation{
		Table:     "consumer_freight_templates",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerLoginLogsTable.Annotation = &entsql.Annotation{
		Table:     "consumer_login_logs",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerLogisticsTrackingsTable.Annotation = &entsql.Annotation{
		Table:     "consumer_logistics_trackings",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerMediaFilesTable.Annotation = &entsql.Annotation{
		Table:     "consumer_media_files",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerPaymentOrdersTable.Annotation = &entsql.Annotation{
		Table:     "consumer_payment_orders",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ConsumerSmsLogsTable.Annotation = &entsql.Annotation{
		Table:     "consumer_sms_logs",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
