// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-admin/app/consumer/service/internal/data/ent/consumer"
	"go-wind-admin/app/consumer/service/internal/data/ent/financeaccount"
	"go-wind-admin/app/consumer/service/internal/data/ent/financetransaction"
	"go-wind-admin/app/consumer/service/internal/data/ent/freighttemplate"
	"go-wind-admin/app/consumer/service/internal/data/ent/loginlog"
	"go-wind-admin/app/consumer/service/internal/data/ent/logisticstracking"
	"go-wind-admin/app/consumer/service/internal/data/ent/mediafile"
	"go-wind-admin/app/consumer/service/internal/data/ent/paymentorder"
	"go-wind-admin/app/consumer/service/internal/data/ent/smslog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 9)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   consumer.Table,
			Columns: consumer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: consumer.FieldID,
			},
		},
		Type: "Consumer",
		Fields: map[string]*sqlgraph.FieldSpec{
			consumer.FieldCreatedBy:      {Type: field.TypeUint32, Column: consumer.FieldCreatedBy},
			consumer.FieldUpdatedBy:      {Type: field.TypeUint32, Column: consumer.FieldUpdatedBy},
			consumer.FieldDeletedBy:      {Type: field.TypeUint32, Column: consumer.FieldDeletedBy},
			consumer.FieldCreatedAt:      {Type: field.TypeTime, Column: consumer.FieldCreatedAt},
			consumer.FieldUpdatedAt:      {Type: field.TypeTime, Column: consumer.FieldUpdatedAt},
			consumer.FieldDeletedAt:      {Type: field.TypeTime, Column: consumer.FieldDeletedAt},
			consumer.FieldTenantID:       {Type: field.TypeUint32, Column: consumer.FieldTenantID},
			consumer.FieldPhone:          {Type: field.TypeString, Column: consumer.FieldPhone},
			consumer.FieldEmail:          {Type: field.TypeString, Column: consumer.FieldEmail},
			consumer.FieldNickname:       {Type: field.TypeString, Column: consumer.FieldNickname},
			consumer.FieldAvatar:         {Type: field.TypeString, Column: consumer.FieldAvatar},
			consumer.FieldPasswordHash:   {Type: field.TypeString, Column: consumer.FieldPasswordHash},
			consumer.FieldWechatOpenid:   {Type: field.TypeString, Column: consumer.FieldWechatOpenid},
			consumer.FieldWechatUnionid:  {Type: field.TypeString, Column: consumer.FieldWechatUnionid},
			consumer.FieldStatus:         {Type: field.TypeEnum, Column: consumer.FieldStatus},
			consumer.FieldRiskScore:      {Type: field.TypeInt, Column: consumer.FieldRiskScore},
			consumer.FieldLoginFailCount: {Type: field.TypeInt, Column: consumer.FieldLoginFailCount},
			consumer.FieldLockedUntil:    {Type: field.TypeTime, Column: consumer.FieldLockedUntil},
			consumer.FieldLastLoginAt:    {Type: field.TypeTime, Column: consumer.FieldLastLoginAt},
			consumer.FieldLastLoginIP:    {Type: field.TypeString, Column: consumer.FieldLastLoginIP},
			consumer.FieldDeactivatedAt:  {Type: field.TypeTime, Column: consumer.FieldDeactivatedAt},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   financeaccount.Table,
			Columns: financeaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: financeaccount.FieldID,
			},
		},
		Type: "FinanceAccount",
		Fields: map[string]*sqlgraph.FieldSpec{
			financeaccount.FieldCreatedAt:     {Type: field.TypeTime, Column: financeaccount.FieldCreatedAt},
			financeaccount.FieldUpdatedAt:     {Type: field.TypeTime, Column: financeaccount.FieldUpdatedAt},
			financeaccount.FieldDeletedAt:     {Type: field.TypeTime, Column: financeaccount.FieldDeletedAt},
			financeaccount.FieldTenantID:      {Type: field.TypeUint32, Column: financeaccount.FieldTenantID},
			financeaccount.FieldConsumerID:    {Type: field.TypeUint32, Column: financeaccount.FieldConsumerID},
			financeaccount.FieldBalance:       {Type: field.TypeString, Column: financeaccount.FieldBalance},
			financeaccount.FieldFrozenBalance: {Type: field.TypeString, Column: financeaccount.FieldFrozenBalance},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   financetransaction.Table,
			Columns: financetransaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: financetransaction.FieldID,
			},
		},
		Type: "FinanceTransaction",
		Fields: map[string]*sqlgraph.FieldSpec{
			financetransaction.FieldCreatedAt:       {Type: field.TypeTime, Column: financetransaction.FieldCreatedAt},
			financetransaction.FieldTenantID:        {Type: field.TypeUint32, Column: financetransaction.FieldTenantID},
			financetransaction.FieldConsumerID:      {Type: field.TypeUint32, Column: financetransaction.FieldConsumerID},
			financetransaction.FieldTransactionNo:   {Type: field.TypeString, Column: financetransaction.FieldTransactionNo},
			financetransaction.FieldTransactionType: {Type: field.TypeEnum, Column: financetransaction.FieldTransactionType},
			financetransaction.FieldAmount:          {Type: field.TypeString, Column: financetransaction.FieldAmount},
			financetransaction.FieldBalanceBefore:   {Type: field.TypeString, Column: financetransaction.FieldBalanceBefore},
			financetransaction.FieldBalanceAfter:    {Type: field.TypeString, Column: financetransaction.FieldBalanceAfter},
			financetransaction.FieldDescription:     {Type: field.TypeString, Column: financetransaction.FieldDescription},
			financetransaction.FieldRelatedOrderNo:  {Type: field.TypeString, Column: financetransaction.FieldRelatedOrderNo},
			financetransaction.FieldOperatorID:      {Type: field.TypeUint32, Column: financetransaction.FieldOperatorID},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   freighttemplate.Table,
			Columns: freighttemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: freighttemplate.FieldID,
			},
		},
		Type: "FreightTemplate",
		Fields: map[string]*sqlgraph.FieldSpec{
			freighttemplate.FieldCreatedBy:         {Type: field.TypeUint32, Column: freighttemplate.FieldCreatedBy},
			freighttemplate.FieldUpdatedBy:         {Type: field.TypeUint32, Column: freighttemplate.FieldUpdatedBy},
			freighttemplate.FieldDeletedBy:         {Type: field.TypeUint32, Column: freighttemplate.FieldDeletedBy},
			freighttemplate.FieldCreatedAt:         {Type: field.TypeTime, Column: freighttemplate.FieldCreatedAt},
			freighttemplate.FieldUpdatedAt:         {Type: field.TypeTime, Column: freighttemplate.FieldUpdatedAt},
			freighttemplate.FieldDeletedAt:         {Type: field.TypeTime, Column: freighttemplate.FieldDeletedAt},
			freighttemplate.FieldTenantID:          {Type: field.TypeUint32, Column: freighttemplate.FieldTenantID},
			freighttemplate.FieldName:              {Type: field.TypeString, Column: freighttemplate.FieldName},
			freighttemplate.FieldCalculationType:   {Type: field.TypeEnum, Column: freighttemplate.FieldCalculationType},
			freighttemplate.FieldFirstWeight:       {Type: field.TypeString, Column: freighttemplate.FieldFirstWeight},
			freighttemplate.FieldFirstPrice:        {Type: field.TypeString, Column: freighttemplate.FieldFirstPrice},
			freighttemplate.FieldAdditionalWeight:  {Type: field.TypeString, Column: freighttemplate.FieldAdditionalWeight},
			freighttemplate.FieldAdditionalPrice:   {Type: field.TypeString, Column: freighttemplate.FieldAdditionalPrice},
			freighttemplate.FieldRegionRules:       {Type: field.TypeJSON, Column: freighttemplate.FieldRegionRules},
			freighttemplate.FieldFreeShippingRules: {Type: field.TypeJSON, Column: freighttemplate.FieldFreeShippingRules},
			freighttemplate.FieldIsActive:          {Type: field.TypeBool, Column: freighttemplate.FieldIsActive},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   loginlog.Table,
			Columns: loginlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: loginlog.FieldID,
			},
		},
		Type: "LoginLog",
		Fields: map[string]*sqlgraph.FieldSpec{
			loginlog.FieldTenantID:   {Type: field.TypeUint32, Column: loginlog.FieldTenantID},
			loginlog.FieldConsumerID: {Type: field.TypeUint32, Column: loginlog.FieldConsumerID},
			loginlog.FieldPhone:      {Type: field.TypeString, Column: loginlog.FieldPhone},
			loginlog.FieldLoginType:  {Type: field.TypeEnum, Column: loginlog.FieldLoginType},
			loginlog.FieldSuccess:    {Type: field.TypeBool, Column: loginlog.FieldSuccess},
			loginlog.FieldFailReason: {Type: field.TypeString, Column: loginlog.FieldFailReason},
			loginlog.FieldIPAddress:  {Type: field.TypeString, Column: loginlog.FieldIPAddress},
			loginlog.FieldUserAgent:  {Type: field.TypeString, Column: loginlog.FieldUserAgent},
			loginlog.FieldDeviceType: {Type: field.TypeString, Column: loginlog.FieldDeviceType},
			loginlog.FieldLoginAt:    {Type: field.TypeTime, Column: loginlog.FieldLoginAt},
		},
	}
	graph.Nodes[5] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   logisticstracking.Table,
			Columns: logisticstracking.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: logisticstracking.FieldID,
			},
		},
		Type: "LogisticsTracking",
		Fields: map[string]*sqlgraph.FieldSpec{
			logisticstracking.FieldCreatedAt:      {Type: field.TypeTime, Column: logisticstracking.FieldCreatedAt},
			logisticstracking.FieldTenantID:       {Type: field.TypeUint32, Column: logisticstracking.FieldTenantID},
			logisticstracking.FieldTrackingNo:     {Type: field.TypeString, Column: logisticstracking.FieldTrackingNo},
			logisticstracking.FieldCourierCompany: {Type: field.TypeString, Column: logisticstracking.FieldCourierCompany},
			logisticstracking.FieldStatus:         {Type: field.TypeEnum, Column: logisticstracking.FieldStatus},
			logisticstracking.FieldTrackingInfo:   {Type: field.TypeJSON, Column: logisticstracking.FieldTrackingInfo},
			logisticstracking.FieldLastUpdatedAt:  {Type: field.TypeTime, Column: logisticstracking.FieldLastUpdatedAt},
		},
	}
	graph.Nodes[6] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   mediafile.Table,
			Columns: mediafile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: mediafile.FieldID,
			},
		},
		Type: "MediaFile",
		Fields: map[string]*sqlgraph.FieldSpec{
			mediafile.FieldCreatedAt:    {Type: field.TypeTime, Column: mediafile.FieldCreatedAt},
			mediafile.FieldTenantID:     {Type: field.TypeUint32, Column: mediafile.FieldTenantID},
			mediafile.FieldConsumerID:   {Type: field.TypeUint32, Column: mediafile.FieldConsumerID},
			mediafile.FieldFileName:     {Type: field.TypeString, Column: mediafile.FieldFileName},
			mediafile.FieldFileType:     {Type: field.TypeEnum, Column: mediafile.FieldFileType},
			mediafile.FieldFileFormat:   {Type: field.TypeString, Column: mediafile.FieldFileFormat},
			mediafile.FieldFileSize:     {Type: field.TypeUint64, Column: mediafile.FieldFileSize},
			mediafile.FieldFileURL:      {Type: field.TypeString, Column: mediafile.FieldFileURL},
			mediafile.FieldThumbnailURL: {Type: field.TypeString, Column: mediafile.FieldThumbnailURL},
			mediafile.FieldOssBucket:    {Type: field.TypeString, Column: mediafile.FieldOssBucket},
			mediafile.FieldOssKey:       {Type: field.TypeString, Column: mediafile.FieldOssKey},
			mediafile.FieldIsDeleted:    {Type: field.TypeBool, Column: mediafile.FieldIsDeleted},
			mediafile.FieldDeletedAt:    {Type: field.TypeTime, Column: mediafile.FieldDeletedAt},
		},
	}
	graph.Nodes[7] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   paymentorder.Table,
			Columns: paymentorder.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: paymentorder.FieldID,
			},
		},
		Type: "PaymentOrder",
		Fields: map[string]*sqlgraph.FieldSpec{
			paymentorder.FieldCreatedAt:     {Type: field.TypeTime, Column: paymentorder.FieldCreatedAt},
			paymentorder.FieldUpdatedAt:     {Type: field.TypeTime, Column: paymentorder.FieldUpdatedAt},
			paymentorder.FieldDeletedAt:     {Type: field.TypeTime, Column: paymentorder.FieldDeletedAt},
			paymentorder.FieldTenantID:      {Type: field.TypeUint32, Column: paymentorder.FieldTenantID},
			paymentorder.FieldOrderNo:       {Type: field.TypeString, Column: paymentorder.FieldOrderNo},
			paymentorder.FieldConsumerID:    {Type: field.TypeUint32, Column: paymentorder.FieldConsumerID},
			paymentorder.FieldPaymentMethod: {Type: field.TypeEnum, Column: paymentorder.FieldPaymentMethod},
			paymentorder.FieldPaymentType:   {Type: field.TypeEnum, Column: paymentorder.FieldPaymentType},
			paymentorder.FieldAmount:        {Type: field.TypeString, Column: paymentorder.FieldAmount},
			paymentorder.FieldStatus:        {Type: field.TypeEnum, Column: paymentorder.FieldStatus},
			paymentorder.FieldTransactionID: {Type: field.TypeString, Column: paymentorder.FieldTransactionID},
			paymentorder.FieldCallbackData:  {Type: field.TypeString, Column: paymentorder.FieldCallbackData},
			paymentorder.FieldPaidAt:        {Type: field.TypeTime, Column: paymentorder.FieldPaidAt},
			paymentorder.FieldClosedAt:      {Type: field.TypeTime, Column: paymentorder.FieldClosedAt},
			paymentorder.FieldExpiresAt:     {Type: field.TypeTime, Column: paymentorder.FieldExpiresAt},
		},
	}
	graph.Nodes[8] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   smslog.Table,
			Columns: smslog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: smslog.FieldID,
			},
		},
		Type: "SMSLog",
		Fields: map[string]*sqlgraph.FieldSpec{
			smslog.FieldTenantID:     {Type: field.TypeUint32, Column: smslog.FieldTenantID},
			smslog.FieldPhone:        {Type: field.TypeString, Column: smslog.FieldPhone},
			smslog.FieldSmsType:      {Type: field.TypeEnum, Column: smslog.FieldSmsType},
			smslog.FieldContent:      {Type: field.TypeString, Column: smslog.FieldContent},
			smslog.FieldCode:         {Type: field.TypeString, Column: smslog.FieldCode},
			smslog.FieldChannel:      {Type: field.TypeEnum, Column: smslog.FieldChannel},
			smslog.FieldStatus:       {Type: field.TypeEnum, Column: smslog.FieldStatus},
			smslog.FieldErrorMessage: {Type: field.TypeString, Column: smslog.FieldErrorMessage},
			smslog.FieldSentAt:       {Type: field.TypeTime, Column: smslog.FieldSentAt},
			smslog.FieldExpiresAt:    {Type: field.TypeTime, Column: smslog.FieldExpiresAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *ConsumerQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ConsumerQuery builder.
func (_q *ConsumerQuery) Filter() *ConsumerFilter {
	return &ConsumerFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *ConsumerMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ConsumerMutation builder.
func (m *ConsumerMutation) Filter() *ConsumerFilter {
	return &ConsumerFilter{config: m.config, predicateAdder: m}
}

// ConsumerFilter provides a generic filtering capability at runtime for ConsumerQuery.
type ConsumerFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ConsumerFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *ConsumerFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(consumer.FieldID))
}

// WhereCreatedBy applies the entql uint32 predicate on the created_by field.
func (f *ConsumerFilter) WhereCreatedBy(p entql.Uint32P) {
	f.Where(p.Field(consumer.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql uint32 predicate on the updated_by field.
func (f *ConsumerFilter) WhereUpdatedBy(p entql.Uint32P) {
	f.Where(p.Field(consumer.FieldUpdatedBy))
}

// WhereDeletedBy applies the entql uint32 predicate on the deleted_by field.
func (f *ConsumerFilter) WhereDeletedBy(p entql.Uint32P) {
	f.Where(p.Field(consumer.FieldDeletedBy))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *ConsumerFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(consumer.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *ConsumerFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(consumer.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *ConsumerFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(consumer.FieldDeletedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *ConsumerFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(consumer.FieldTenantID))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *ConsumerFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(consumer.FieldPhone))
}

// WhereEmail applies the entql string predicate on the email field.
func (f *ConsumerFilter) WhereEmail(p entql.StringP) {
	f.Where(p.Field(consumer.FieldEmail))
}

// WhereNickname applies the entql string predicate on the nickname field.
func (f *ConsumerFilter) WhereNickname(p entql.StringP) {
	f.Where(p.Field(consumer.FieldNickname))
}

// WhereAvatar applies the entql string predicate on the avatar field.
func (f *ConsumerFilter) WhereAvatar(p entql.StringP) {
	f.Where(p.Field(consumer.FieldAvatar))
}

// WherePasswordHash applies the entql string predicate on the password_hash field.
func (f *ConsumerFilter) WherePasswordHash(p entql.StringP) {
	f.Where(p.Field(consumer.FieldPasswordHash))
}

// WhereWechatOpenid applies the entql string predicate on the wechat_openid field.
func (f *ConsumerFilter) WhereWechatOpenid(p entql.StringP) {
	f.Where(p.Field(consumer.FieldWechatOpenid))
}

// WhereWechatUnionid applies the entql string predicate on the wechat_unionid field.
func (f *ConsumerFilter) WhereWechatUnionid(p entql.StringP) {
	f.Where(p.Field(consumer.FieldWechatUnionid))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *ConsumerFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(consumer.FieldStatus))
}

// WhereRiskScore applies the entql int predicate on the risk_score field.
func (f *ConsumerFilter) WhereRiskScore(p entql.IntP) {
	f.Where(p.Field(consumer.FieldRiskScore))
}

// WhereLoginFailCount applies the entql int predicate on the login_fail_count field.
func (f *ConsumerFilter) WhereLoginFailCount(p entql.IntP) {
	f.Where(p.Field(consumer.FieldLoginFailCount))
}

// WhereLockedUntil applies the entql time.Time predicate on the locked_until field.
func (f *ConsumerFilter) WhereLockedUntil(p entql.TimeP) {
	f.Where(p.Field(consumer.FieldLockedUntil))
}

// WhereLastLoginAt applies the entql time.Time predicate on the last_login_at field.
func (f *ConsumerFilter) WhereLastLoginAt(p entql.TimeP) {
	f.Where(p.Field(consumer.FieldLastLoginAt))
}

// WhereLastLoginIP applies the entql string predicate on the last_login_ip field.
func (f *ConsumerFilter) WhereLastLoginIP(p entql.StringP) {
	f.Where(p.Field(consumer.FieldLastLoginIP))
}

// WhereDeactivatedAt applies the entql time.Time predicate on the deactivated_at field.
func (f *ConsumerFilter) WhereDeactivatedAt(p entql.TimeP) {
	f.Where(p.Field(consumer.FieldDeactivatedAt))
}

// addPredicate implements the predicateAdder interface.
func (_q *FinanceAccountQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the FinanceAccountQuery builder.
func (_q *FinanceAccountQuery) Filter() *FinanceAccountFilter {
	return &FinanceAccountFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *FinanceAccountMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the FinanceAccountMutation builder.
func (m *FinanceAccountMutation) Filter() *FinanceAccountFilter {
	return &FinanceAccountFilter{config: m.config, predicateAdder: m}
}

// FinanceAccountFilter provides a generic filtering capability at runtime for FinanceAccountQuery.
type FinanceAccountFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *FinanceAccountFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *FinanceAccountFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(financeaccount.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *FinanceAccountFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(financeaccount.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *FinanceAccountFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(financeaccount.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *FinanceAccountFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(financeaccount.FieldDeletedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *FinanceAccountFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(financeaccount.FieldTenantID))
}

// WhereConsumerID applies the entql uint32 predicate on the consumer_id field.
func (f *FinanceAccountFilter) WhereConsumerID(p entql.Uint32P) {
	f.Where(p.Field(financeaccount.FieldConsumerID))
}

// WhereBalance applies the entql string predicate on the balance field.
func (f *FinanceAccountFilter) WhereBalance(p entql.StringP) {
	f.Where(p.Field(financeaccount.FieldBalance))
}

// WhereFrozenBalance applies the entql string predicate on the frozen_balance field.
func (f *FinanceAccountFilter) WhereFrozenBalance(p entql.StringP) {
	f.Where(p.Field(financeaccount.FieldFrozenBalance))
}

// addPredicate implements the predicateAdder interface.
func (_q *FinanceTransactionQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the FinanceTransactionQuery builder.
func (_q *FinanceTransactionQuery) Filter() *FinanceTransactionFilter {
	return &FinanceTransactionFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *FinanceTransactionMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the FinanceTransactionMutation builder.
func (m *FinanceTransactionMutation) Filter() *FinanceTransactionFilter {
	return &FinanceTransactionFilter{config: m.config, predicateAdder: m}
}

// FinanceTransactionFilter provides a generic filtering capability at runtime for FinanceTransactionQuery.
type FinanceTransactionFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *FinanceTransactionFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *FinanceTransactionFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(financetransaction.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *FinanceTransactionFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(financetransaction.FieldCreatedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *FinanceTransactionFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(financetransaction.FieldTenantID))
}

// WhereConsumerID applies the entql uint32 predicate on the consumer_id field.
func (f *FinanceTransactionFilter) WhereConsumerID(p entql.Uint32P) {
	f.Where(p.Field(financetransaction.FieldConsumerID))
}

// WhereTransactionNo applies the entql string predicate on the transaction_no field.
func (f *FinanceTransactionFilter) WhereTransactionNo(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldTransactionNo))
}

// WhereTransactionType applies the entql string predicate on the transaction_type field.
func (f *FinanceTransactionFilter) WhereTransactionType(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldTransactionType))
}

// WhereAmount applies the entql string predicate on the amount field.
func (f *FinanceTransactionFilter) WhereAmount(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldAmount))
}

// WhereBalanceBefore applies the entql string predicate on the balance_before field.
func (f *FinanceTransactionFilter) WhereBalanceBefore(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldBalanceBefore))
}

// WhereBalanceAfter applies the entql string predicate on the balance_after field.
func (f *FinanceTransactionFilter) WhereBalanceAfter(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldBalanceAfter))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *FinanceTransactionFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldDescription))
}

// WhereRelatedOrderNo applies the entql string predicate on the related_order_no field.
func (f *FinanceTransactionFilter) WhereRelatedOrderNo(p entql.StringP) {
	f.Where(p.Field(financetransaction.FieldRelatedOrderNo))
}

// WhereOperatorID applies the entql uint32 predicate on the operator_id field.
func (f *FinanceTransactionFilter) WhereOperatorID(p entql.Uint32P) {
	f.Where(p.Field(financetransaction.FieldOperatorID))
}

// addPredicate implements the predicateAdder interface.
func (_q *FreightTemplateQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the FreightTemplateQuery builder.
func (_q *FreightTemplateQuery) Filter() *FreightTemplateFilter {
	return &FreightTemplateFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *FreightTemplateMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the FreightTemplateMutation builder.
func (m *FreightTemplateMutation) Filter() *FreightTemplateFilter {
	return &FreightTemplateFilter{config: m.config, predicateAdder: m}
}

// FreightTemplateFilter provides a generic filtering capability at runtime for FreightTemplateQuery.
type FreightTemplateFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *FreightTemplateFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *FreightTemplateFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(freighttemplate.FieldID))
}

// WhereCreatedBy applies the entql uint32 predicate on the created_by field.
func (f *FreightTemplateFilter) WhereCreatedBy(p entql.Uint32P) {
	f.Where(p.Field(freighttemplate.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql uint32 predicate on the updated_by field.
func (f *FreightTemplateFilter) WhereUpdatedBy(p entql.Uint32P) {
	f.Where(p.Field(freighttemplate.FieldUpdatedBy))
}

// WhereDeletedBy applies the entql uint32 predicate on the deleted_by field.
func (f *FreightTemplateFilter) WhereDeletedBy(p entql.Uint32P) {
	f.Where(p.Field(freighttemplate.FieldDeletedBy))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *FreightTemplateFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(freighttemplate.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *FreightTemplateFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(freighttemplate.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *FreightTemplateFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(freighttemplate.FieldDeletedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *FreightTemplateFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(freighttemplate.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *FreightTemplateFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(freighttemplate.FieldName))
}

// WhereCalculationType applies the entql string predicate on the calculation_type field.
func (f *FreightTemplateFilter) WhereCalculationType(p entql.StringP) {
	f.Where(p.Field(freighttemplate.FieldCalculationType))
}

// WhereFirstWeight applies the entql string predicate on the first_weight field.
func (f *FreightTemplateFilter) WhereFirstWeight(p entql.StringP) {
	f.Where(p.Field(freighttemplate.FieldFirstWeight))
}

// WhereFirstPrice applies the entql string predicate on the first_price field.
func (f *FreightTemplateFilter) WhereFirstPrice(p entql.StringP) {
	f.Where(p.Field(freighttemplate.FieldFirstPrice))
}

// WhereAdditionalWeight applies the entql string predicate on the additional_weight field.
func (f *FreightTemplateFilter) WhereAdditionalWeight(p entql.StringP) {
	f.Where(p.Field(freighttemplate.FieldAdditionalWeight))
}

// WhereAdditionalPrice applies the entql string predicate on the additional_price field.
func (f *FreightTemplateFilter) WhereAdditionalPrice(p entql.StringP) {
	f.Where(p.Field(freighttemplate.FieldAdditionalPrice))
}

// WhereRegionRules applies the entql json.RawMessage predicate on the region_rules field.
func (f *FreightTemplateFilter) WhereRegionRules(p entql.BytesP) {
	f.Where(p.Field(freighttemplate.FieldRegionRules))
}

// WhereFreeShippingRules applies the entql json.RawMessage predicate on the free_shipping_rules field.
func (f *FreightTemplateFilter) WhereFreeShippingRules(p entql.BytesP) {
	f.Where(p.Field(freighttemplate.FieldFreeShippingRules))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *FreightTemplateFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(freighttemplate.FieldIsActive))
}

// addPredicate implements the predicateAdder interface.
func (_q *LoginLogQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the LoginLogQuery builder.
func (_q *LoginLogQuery) Filter() *LoginLogFilter {
	return &LoginLogFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *LoginLogMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the LoginLogMutation builder.
func (m *LoginLogMutation) Filter() *LoginLogFilter {
	return &LoginLogFilter{config: m.config, predicateAdder: m}
}

// LoginLogFilter provides a generic filtering capability at runtime for LoginLogQuery.
type LoginLogFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *LoginLogFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *LoginLogFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(loginlog.FieldID))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *LoginLogFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(loginlog.FieldTenantID))
}

// WhereConsumerID applies the entql uint32 predicate on the consumer_id field.
func (f *LoginLogFilter) WhereConsumerID(p entql.Uint32P) {
	f.Where(p.Field(loginlog.FieldConsumerID))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *LoginLogFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(loginlog.FieldPhone))
}

// WhereLoginType applies the entql string predicate on the login_type field.
func (f *LoginLogFilter) WhereLoginType(p entql.StringP) {
	f.Where(p.Field(loginlog.FieldLoginType))
}

// WhereSuccess applies the entql bool predicate on the success field.
func (f *LoginLogFilter) WhereSuccess(p entql.BoolP) {
	f.Where(p.Field(loginlog.FieldSuccess))
}

// WhereFailReason applies the entql string predicate on the fail_reason field.
func (f *LoginLogFilter) WhereFailReason(p entql.StringP) {
	f.Where(p.Field(loginlog.FieldFailReason))
}

// WhereIPAddress applies the entql string predicate on the ip_address field.
func (f *LoginLogFilter) WhereIPAddress(p entql.StringP) {
	f.Where(p.Field(loginlog.FieldIPAddress))
}

// WhereUserAgent applies the entql string predicate on the user_agent field.
func (f *LoginLogFilter) WhereUserAgent(p entql.StringP) {
	f.Where(p.Field(loginlog.FieldUserAgent))
}

// WhereDeviceType applies the entql string predicate on the device_type field.
func (f *LoginLogFilter) WhereDeviceType(p entql.StringP) {
	f.Where(p.Field(loginlog.FieldDeviceType))
}

// WhereLoginAt applies the entql time.Time predicate on the login_at field.
func (f *LoginLogFilter) WhereLoginAt(p entql.TimeP) {
	f.Where(p.Field(loginlog.FieldLoginAt))
}

// addPredicate implements the predicateAdder interface.
func (_q *LogisticsTrackingQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the LogisticsTrackingQuery builder.
func (_q *LogisticsTrackingQuery) Filter() *LogisticsTrackingFilter {
	return &LogisticsTrackingFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *LogisticsTrackingMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the LogisticsTrackingMutation builder.
func (m *LogisticsTrackingMutation) Filter() *LogisticsTrackingFilter {
	return &LogisticsTrackingFilter{config: m.config, predicateAdder: m}
}

// LogisticsTrackingFilter provides a generic filtering capability at runtime for LogisticsTrackingQuery.
type LogisticsTrackingFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *LogisticsTrackingFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[5].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *LogisticsTrackingFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(logisticstracking.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *LogisticsTrackingFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(logisticstracking.FieldCreatedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *LogisticsTrackingFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(logisticstracking.FieldTenantID))
}

// WhereTrackingNo applies the entql string predicate on the tracking_no field.
func (f *LogisticsTrackingFilter) WhereTrackingNo(p entql.StringP) {
	f.Where(p.Field(logisticstracking.FieldTrackingNo))
}

// WhereCourierCompany applies the entql string predicate on the courier_company field.
func (f *LogisticsTrackingFilter) WhereCourierCompany(p entql.StringP) {
	f.Where(p.Field(logisticstracking.FieldCourierCompany))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *LogisticsTrackingFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(logisticstracking.FieldStatus))
}

// WhereTrackingInfo applies the entql json.RawMessage predicate on the tracking_info field.
func (f *LogisticsTrackingFilter) WhereTrackingInfo(p entql.BytesP) {
	f.Where(p.Field(logisticstracking.FieldTrackingInfo))
}

// WhereLastUpdatedAt applies the entql time.Time predicate on the last_updated_at field.
func (f *LogisticsTrackingFilter) WhereLastUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(logisticstracking.FieldLastUpdatedAt))
}

// addPredicate implements the predicateAdder interface.
func (_q *MediaFileQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the MediaFileQuery builder.
func (_q *MediaFileQuery) Filter() *MediaFileFilter {
	return &MediaFileFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *MediaFileMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the MediaFileMutation builder.
func (m *MediaFileMutation) Filter() *MediaFileFilter {
	return &MediaFileFilter{config: m.config, predicateAdder: m}
}

// MediaFileFilter provides a generic filtering capability at runtime for MediaFileQuery.
type MediaFileFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *MediaFileFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[6].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *MediaFileFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(mediafile.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *MediaFileFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(mediafile.FieldCreatedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *MediaFileFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(mediafile.FieldTenantID))
}

// WhereConsumerID applies the entql uint32 predicate on the consumer_id field.
func (f *MediaFileFilter) WhereConsumerID(p entql.Uint32P) {
	f.Where(p.Field(mediafile.FieldConsumerID))
}

// WhereFileName applies the entql string predicate on the file_name field.
func (f *MediaFileFilter) WhereFileName(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldFileName))
}

// WhereFileType applies the entql string predicate on the file_type field.
func (f *MediaFileFilter) WhereFileType(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldFileType))
}

// WhereFileFormat applies the entql string predicate on the file_format field.
func (f *MediaFileFilter) WhereFileFormat(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldFileFormat))
}

// WhereFileSize applies the entql uint64 predicate on the file_size field.
func (f *MediaFileFilter) WhereFileSize(p entql.Uint64P) {
	f.Where(p.Field(mediafile.FieldFileSize))
}

// WhereFileURL applies the entql string predicate on the file_url field.
func (f *MediaFileFilter) WhereFileURL(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldFileURL))
}

// WhereThumbnailURL applies the entql string predicate on the thumbnail_url field.
func (f *MediaFileFilter) WhereThumbnailURL(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldThumbnailURL))
}

// WhereOssBucket applies the entql string predicate on the oss_bucket field.
func (f *MediaFileFilter) WhereOssBucket(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldOssBucket))
}

// WhereOssKey applies the entql string predicate on the oss_key field.
func (f *MediaFileFilter) WhereOssKey(p entql.StringP) {
	f.Where(p.Field(mediafile.FieldOssKey))
}

// WhereIsDeleted applies the entql bool predicate on the is_deleted field.
func (f *MediaFileFilter) WhereIsDeleted(p entql.BoolP) {
	f.Where(p.Field(mediafile.FieldIsDeleted))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *MediaFileFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(mediafile.FieldDeletedAt))
}

// addPredicate implements the predicateAdder interface.
func (_q *PaymentOrderQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the PaymentOrderQuery builder.
func (_q *PaymentOrderQuery) Filter() *PaymentOrderFilter {
	return &PaymentOrderFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *PaymentOrderMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the PaymentOrderMutation builder.
func (m *PaymentOrderMutation) Filter() *PaymentOrderFilter {
	return &PaymentOrderFilter{config: m.config, predicateAdder: m}
}

// PaymentOrderFilter provides a generic filtering capability at runtime for PaymentOrderQuery.
type PaymentOrderFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *PaymentOrderFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[7].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *PaymentOrderFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(paymentorder.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *PaymentOrderFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(paymentorder.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *PaymentOrderFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(paymentorder.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *PaymentOrderFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(paymentorder.FieldDeletedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *PaymentOrderFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(paymentorder.FieldTenantID))
}

// WhereOrderNo applies the entql string predicate on the order_no field.
func (f *PaymentOrderFilter) WhereOrderNo(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldOrderNo))
}

// WhereConsumerID applies the entql uint32 predicate on the consumer_id field.
func (f *PaymentOrderFilter) WhereConsumerID(p entql.Uint32P) {
	f.Where(p.Field(paymentorder.FieldConsumerID))
}

// WherePaymentMethod applies the entql string predicate on the payment_method field.
func (f *PaymentOrderFilter) WherePaymentMethod(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldPaymentMethod))
}

// WherePaymentType applies the entql string predicate on the payment_type field.
func (f *PaymentOrderFilter) WherePaymentType(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldPaymentType))
}

// WhereAmount applies the entql string predicate on the amount field.
func (f *PaymentOrderFilter) WhereAmount(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldAmount))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *PaymentOrderFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldStatus))
}

// WhereTransactionID applies the entql string predicate on the transaction_id field.
func (f *PaymentOrderFilter) WhereTransactionID(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldTransactionID))
}

// WhereCallbackData applies the entql string predicate on the callback_data field.
func (f *PaymentOrderFilter) WhereCallbackData(p entql.StringP) {
	f.Where(p.Field(paymentorder.FieldCallbackData))
}

// WherePaidAt applies the entql time.Time predicate on the paid_at field.
func (f *PaymentOrderFilter) WherePaidAt(p entql.TimeP) {
	f.Where(p.Field(paymentorder.FieldPaidAt))
}

// WhereClosedAt applies the entql time.Time predicate on the closed_at field.
func (f *PaymentOrderFilter) WhereClosedAt(p entql.TimeP) {
	f.Where(p.Field(paymentorder.FieldClosedAt))
}

// WhereExpiresAt applies the entql time.Time predicate on the expires_at field.
func (f *PaymentOrderFilter) WhereExpiresAt(p entql.TimeP) {
	f.Where(p.Field(paymentorder.FieldExpiresAt))
}

// addPredicate implements the predicateAdder interface.
func (_q *SMSLogQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SMSLogQuery builder.
func (_q *SMSLogQuery) Filter() *SMSLogFilter {
	return &SMSLogFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SMSLogMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SMSLogMutation builder.
func (m *SMSLogMutation) Filter() *SMSLogFilter {
	return &SMSLogFilter{config: m.config, predicateAdder: m}
}

// SMSLogFilter provides a generic filtering capability at runtime for SMSLogQuery.
type SMSLogFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SMSLogFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[8].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *SMSLogFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(smslog.FieldID))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *SMSLogFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(smslog.FieldTenantID))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *SMSLogFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(smslog.FieldPhone))
}

// WhereSmsType applies the entql string predicate on the sms_type field.
func (f *SMSLogFilter) WhereSmsType(p entql.StringP) {
	f.Where(p.Field(smslog.FieldSmsType))
}

// WhereContent applies the entql string predicate on the content field.
func (f *SMSLogFilter) WhereContent(p entql.StringP) {
	f.Where(p.Field(smslog.FieldContent))
}

// WhereCode applies the entql string predicate on the code field.
func (f *SMSLogFilter) WhereCode(p entql.StringP) {
	f.Where(p.Field(smslog.FieldCode))
}

// WhereChannel applies the entql string predicate on the channel field.
func (f *SMSLogFilter) WhereChannel(p entql.StringP) {
	f.Where(p.Field(smslog.FieldChannel))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *SMSLogFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(smslog.FieldStatus))
}

// WhereErrorMessage applies the entql string predicate on the error_message field.
func (f *SMSLogFilter) WhereErrorMessage(p entql.StringP) {
	f.Where(p.Field(smslog.FieldErrorMessage))
}

// WhereSentAt applies the entql time.Time predicate on the sent_at field.
func (f *SMSLogFilter) WhereSentAt(p entql.TimeP) {
	f.Where(p.Field(smslog.FieldSentAt))
}

// WhereExpiresAt applies the entql time.Time predicate on the expires_at field.
func (f *SMSLogFilter) WhereExpiresAt(p entql.TimeP) {
	f.Where(p.Field(smslog.FieldExpiresAt))
}
