// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/financetransaction"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FinanceTransactionCreate is the builder for creating a FinanceTransaction entity.
type FinanceTransactionCreate struct {
	config
	mutation *FinanceTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *FinanceTransactionCreate) SetCreatedAt(v time.Time) *FinanceTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FinanceTransactionCreate) SetNillableCreatedAt(v *time.Time) *FinanceTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *FinanceTransactionCreate) SetTenantID(v uint32) *FinanceTransactionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *FinanceTransactionCreate) SetNillableTenantID(v *uint32) *FinanceTransactionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetConsumerID sets the "consumer_id" field.
func (_c *FinanceTransactionCreate) SetConsumerID(v uint32) *FinanceTransactionCreate {
	_c.mutation.SetConsumerID(v)
	return _c
}

// SetTransactionNo sets the "transaction_no" field.
func (_c *FinanceTransactionCreate) SetTransactionNo(v string) *FinanceTransactionCreate {
	_c.mutation.SetTransactionNo(v)
	return _c
}

// SetTransactionType sets the "transaction_type" field.
func (_c *FinanceTransactionCreate) SetTransactionType(v financetransaction.TransactionType) *FinanceTransactionCreate {
	_c.mutation.SetTransactionType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *FinanceTransactionCreate) SetAmount(v string) *FinanceTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *FinanceTransactionCreate) SetBalanceBefore(v string) *FinanceTransactionCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *FinanceTransactionCreate) SetBalanceAfter(v string) *FinanceTransactionCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FinanceTransactionCreate) SetDescription(v string) *FinanceTransactionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FinanceTransactionCreate) SetNillableDescription(v *string) *FinanceTransactionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRelatedOrderNo sets the "related_order_no" field.
func (_c *FinanceTransactionCreate) SetRelatedOrderNo(v string) *FinanceTransactionCreate {
	_c.mutation.SetRelatedOrderNo(v)
	return _c
}

// SetNillableRelatedOrderNo sets the "related_order_no" field if the given value is not nil.
func (_c *FinanceTransactionCreate) SetNillableRelatedOrderNo(v *string) *FinanceTransactionCreate {
	if v != nil {
		_c.SetRelatedOrderNo(*v)
	}
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *FinanceTransactionCreate) SetOperatorID(v uint32) *FinanceTransactionCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *FinanceTransactionCreate) SetNillableOperatorID(v *uint32) *FinanceTransactionCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FinanceTransactionCreate) SetID(v uint32) *FinanceTransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the FinanceTransactionMutation object of the builder.
func (_c *FinanceTransactionCreate) Mutation() *FinanceTransactionMutation {
	return _c.mutation
}

// Save creates the FinanceTransaction in the database.
func (_c *FinanceTransactionCreate) Save(ctx context.Context) (*FinanceTransaction, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceTransactionCreate) SaveX(ctx context.Context) *FinanceTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinanceTransactionCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := financetransaction.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceTransactionCreate) check() error {
	if _, ok := _c.mutation.ConsumerID(); !ok {
		return &ValidationError{Name: "consumer_id", err: errors.New(`ent: missing required field "FinanceTransaction.consumer_id"`)}
	}
	if _, ok := _c.mutation.TransactionNo(); !ok {
		return &ValidationError{Name: "transaction_no", err: errors.New(`ent: missing required field "FinanceTransaction.transaction_no"`)}
	}
	if v, ok := _c.mutation.TransactionNo(); ok {
		if err := financetransaction.TransactionNoValidator(v); err != nil {
			return &ValidationError{Name: "transaction_no", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.transaction_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TransactionType(); !ok {
		return &ValidationError{Name: "transaction_type", err: errors.New(`ent: missing required field "FinanceTransaction.transaction_type"`)}
	}
	if v, ok := _c.mutation.TransactionType(); ok {
		if err := financetransaction.TransactionTypeValidator(v); err != nil {
			return &ValidationError{Name: "transaction_type", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.transaction_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "FinanceTransaction.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := financetransaction.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "FinanceTransaction.balance_before"`)}
	}
	if v, ok := _c.mutation.BalanceBefore(); ok {
		if err := financetransaction.BalanceBeforeValidator(v); err != nil {
			return &ValidationError{Name: "balance_before", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.balance_before": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "FinanceTransaction.balance_after"`)}
	}
	if v, ok := _c.mutation.BalanceAfter(); ok {
		if err := financetransaction.BalanceAfterValidator(v); err != nil {
			return &ValidationError{Name: "balance_after", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.balance_after": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := financetransaction.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RelatedOrderNo(); ok {
		if err := financetransaction.RelatedOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "related_order_no", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.related_order_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := financetransaction.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "FinanceTransaction.id": %w`, err)}
		}
	}
	return nil
}

func (_c *FinanceTransactionCreate) sqlSave(ctx context.Context) (*FinanceTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceTransactionCreate) createSpec() (*FinanceTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financetransaction.Table, sqlgraph.NewFieldSpec(financetransaction.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(financetransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(financetransaction.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ConsumerID(); ok {
		_spec.SetField(financetransaction.FieldConsumerID, field.TypeUint32, value)
		_node.ConsumerID = value
	}
	if value, ok := _c.mutation.TransactionNo(); ok {
		_spec.SetField(financetransaction.FieldTransactionNo, field.TypeString, value)
		_node.TransactionNo = value
	}
	if value, ok := _c.mutation.TransactionType(); ok {
		_spec.SetField(financetransaction.FieldTransactionType, field.TypeEnum, value)
		_node.TransactionType = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(financetransaction.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(financetransaction.FieldBalanceBefore, field.TypeString, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(financetransaction.FieldBalanceAfter, field.TypeString, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(financetransaction.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.RelatedOrderNo(); ok {
		_spec.SetField(financetransaction.FieldRelatedOrderNo, field.TypeString, value)
		_node.RelatedOrderNo = &value
	}
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(financetransaction.FieldOperatorID, field.TypeUint32, value)
		_node.OperatorID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinanceTransaction.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinanceTransactionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FinanceTransactionCreate) OnConflict(opts ...sql.ConflictOption) *FinanceTransactionUpsertOne {
	_c.conflict = opts
	return &FinanceTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinanceTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinanceTransactionCreate) OnConflictColumns(columns ...string) *FinanceTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinanceTransactionUpsertOne{
		create: _c,
	}
}

type (
	// FinanceTransactionUpsertOne is the builder for "upsert"-ing
	//  one FinanceTransaction node.
	FinanceTransactionUpsertOne struct {
		create *FinanceTransactionCreate
	}

	// FinanceTransactionUpsert is the "OnConflict" setter.
	FinanceTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetConsumerID sets the "consumer_id" field.
func (u *FinanceTransactionUpsert) SetConsumerID(v uint32) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldConsumerID, v)
	return u
}

// UpdateConsumerID sets the "consumer_id" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateConsumerID() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldConsumerID)
	return u
}

// AddConsumerID adds v to the "consumer_id" field.
func (u *FinanceTransactionUpsert) AddConsumerID(v uint32) *FinanceTransactionUpsert {
	u.Add(financetransaction.FieldConsumerID, v)
	return u
}

// SetTransactionNo sets the "transaction_no" field.
func (u *FinanceTransactionUpsert) SetTransactionNo(v string) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldTransactionNo, v)
	return u
}

// UpdateTransactionNo sets the "transaction_no" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateTransactionNo() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldTransactionNo)
	return u
}

// SetTransactionType sets the "transaction_type" field.
func (u *FinanceTransactionUpsert) SetTransactionType(v financetransaction.TransactionType) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldTransactionType, v)
	return u
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateTransactionType() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldTransactionType)
	return u
}

// SetAmount sets the "amount" field.
func (u *FinanceTransactionUpsert) SetAmount(v string) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateAmount() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldAmount)
	return u
}

// SetBalanceBefore sets the "balance_before" field.
func (u *FinanceTransactionUpsert) SetBalanceBefore(v string) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldBalanceBefore, v)
	return u
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateBalanceBefore() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldBalanceBefore)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *FinanceTransactionUpsert) SetBalanceAfter(v string) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateBalanceAfter() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldBalanceAfter)
	return u
}

// SetDescription sets the "description" field.
func (u *FinanceTransactionUpsert) SetDescription(v string) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateDescription() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *FinanceTransactionUpsert) ClearDescription() *FinanceTransactionUpsert {
	u.SetNull(financetransaction.FieldDescription)
	return u
}

// SetRelatedOrderNo sets the "related_order_no" field.
func (u *FinanceTransactionUpsert) SetRelatedOrderNo(v string) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldRelatedOrderNo, v)
	return u
}

// UpdateRelatedOrderNo sets the "related_order_no" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateRelatedOrderNo() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldRelatedOrderNo)
	return u
}

// ClearRelatedOrderNo clears the value of the "related_order_no" field.
func (u *FinanceTransactionUpsert) ClearRelatedOrderNo() *FinanceTransactionUpsert {
	u.SetNull(financetransaction.FieldRelatedOrderNo)
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *FinanceTransactionUpsert) SetOperatorID(v uint32) *FinanceTransactionUpsert {
	u.Set(financetransaction.FieldOperatorID, v)
	return u
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *FinanceTransactionUpsert) UpdateOperatorID() *FinanceTransactionUpsert {
	u.SetExcluded(financetransaction.FieldOperatorID)
	return u
}

// AddOperatorID adds v to the "operator_id" field.
func (u *FinanceTransactionUpsert) AddOperatorID(v uint32) *FinanceTransactionUpsert {
	u.Add(financetransaction.FieldOperatorID, v)
	return u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *FinanceTransactionUpsert) ClearOperatorID() *FinanceTransactionUpsert {
	u.SetNull(financetransaction.FieldOperatorID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.FinanceTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(financetransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FinanceTransactionUpsertOne) UpdateNewValues() *FinanceTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(financetransaction.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(financetransaction.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(financetransaction.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinanceTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FinanceTransactionUpsertOne) Ignore() *FinanceTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinanceTransactionUpsertOne) DoNothing() *FinanceTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinanceTransactionCreate.OnConflict
// documentation for more info.
func (u *FinanceTransactionUpsertOne) Update(set func(*FinanceTransactionUpsert)) *FinanceTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinanceTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetConsumerID sets the "consumer_id" field.
func (u *FinanceTransactionUpsertOne) SetConsumerID(v uint32) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetConsumerID(v)
	})
}

// AddConsumerID adds v to the "consumer_id" field.
func (u *FinanceTransactionUpsertOne) AddConsumerID(v uint32) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.AddConsumerID(v)
	})
}

// UpdateConsumerID sets the "consumer_id" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateConsumerID() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateConsumerID()
	})
}

// SetTransactionNo sets the "transaction_no" field.
func (u *FinanceTransactionUpsertOne) SetTransactionNo(v string) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetTransactionNo(v)
	})
}

// UpdateTransactionNo sets the "transaction_no" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateTransactionNo() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateTransactionNo()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *FinanceTransactionUpsertOne) SetTransactionType(v financetransaction.TransactionType) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateTransactionType() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateTransactionType()
	})
}

// SetAmount sets the "amount" field.
func (u *FinanceTransactionUpsertOne) SetAmount(v string) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateAmount() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *FinanceTransactionUpsertOne) SetBalanceBefore(v string) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateBalanceBefore() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *FinanceTransactionUpsertOne) SetBalanceAfter(v string) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateBalanceAfter() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetDescription sets the "description" field.
func (u *FinanceTransactionUpsertOne) SetDescription(v string) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateDescription() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FinanceTransactionUpsertOne) ClearDescription() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.ClearDescription()
	})
}

// SetRelatedOrderNo sets the "related_order_no" field.
func (u *FinanceTransactionUpsertOne) SetRelatedOrderNo(v string) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetRelatedOrderNo(v)
	})
}

// UpdateRelatedOrderNo sets the "related_order_no" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateRelatedOrderNo() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateRelatedOrderNo()
	})
}

// ClearRelatedOrderNo clears the value of the "related_order_no" field.
func (u *FinanceTransactionUpsertOne) ClearRelatedOrderNo() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.ClearRelatedOrderNo()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *FinanceTransactionUpsertOne) SetOperatorID(v uint32) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *FinanceTransactionUpsertOne) AddOperatorID(v uint32) *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *FinanceTransactionUpsertOne) UpdateOperatorID() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateOperatorID()
	})
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *FinanceTransactionUpsertOne) ClearOperatorID() *FinanceTransactionUpsertOne {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.ClearOperatorID()
	})
}

// Exec executes the query.
func (u *FinanceTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinanceTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinanceTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FinanceTransactionUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FinanceTransactionUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FinanceTransactionCreateBulk is the builder for creating many FinanceTransaction entities in bulk.
type FinanceTransactionCreateBulk struct {
	config
	err      error
	builders []*FinanceTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the FinanceTransaction entities in the database.
func (_c *FinanceTransactionCreateBulk) Save(ctx context.Context) ([]*FinanceTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceTransactionCreateBulk) SaveX(ctx context.Context) []*FinanceTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FinanceTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FinanceTransactionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FinanceTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *FinanceTransactionUpsertBulk {
	_c.conflict = opts
	return &FinanceTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FinanceTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FinanceTransactionCreateBulk) OnConflictColumns(columns ...string) *FinanceTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FinanceTransactionUpsertBulk{
		create: _c,
	}
}

// FinanceTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of FinanceTransaction nodes.
type FinanceTransactionUpsertBulk struct {
	create *FinanceTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FinanceTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(financetransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FinanceTransactionUpsertBulk) UpdateNewValues() *FinanceTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(financetransaction.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(financetransaction.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(financetransaction.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FinanceTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FinanceTransactionUpsertBulk) Ignore() *FinanceTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FinanceTransactionUpsertBulk) DoNothing() *FinanceTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FinanceTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *FinanceTransactionUpsertBulk) Update(set func(*FinanceTransactionUpsert)) *FinanceTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FinanceTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetConsumerID sets the "consumer_id" field.
func (u *FinanceTransactionUpsertBulk) SetConsumerID(v uint32) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetConsumerID(v)
	})
}

// AddConsumerID adds v to the "consumer_id" field.
func (u *FinanceTransactionUpsertBulk) AddConsumerID(v uint32) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.AddConsumerID(v)
	})
}

// UpdateConsumerID sets the "consumer_id" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateConsumerID() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateConsumerID()
	})
}

// SetTransactionNo sets the "transaction_no" field.
func (u *FinanceTransactionUpsertBulk) SetTransactionNo(v string) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetTransactionNo(v)
	})
}

// UpdateTransactionNo sets the "transaction_no" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateTransactionNo() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateTransactionNo()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *FinanceTransactionUpsertBulk) SetTransactionType(v financetransaction.TransactionType) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateTransactionType() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateTransactionType()
	})
}

// SetAmount sets the "amount" field.
func (u *FinanceTransactionUpsertBulk) SetAmount(v string) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateAmount() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *FinanceTransactionUpsertBulk) SetBalanceBefore(v string) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateBalanceBefore() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *FinanceTransactionUpsertBulk) SetBalanceAfter(v string) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateBalanceAfter() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetDescription sets the "description" field.
func (u *FinanceTransactionUpsertBulk) SetDescription(v string) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateDescription() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FinanceTransactionUpsertBulk) ClearDescription() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.ClearDescription()
	})
}

// SetRelatedOrderNo sets the "related_order_no" field.
func (u *FinanceTransactionUpsertBulk) SetRelatedOrderNo(v string) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetRelatedOrderNo(v)
	})
}

// UpdateRelatedOrderNo sets the "related_order_no" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateRelatedOrderNo() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateRelatedOrderNo()
	})
}

// ClearRelatedOrderNo clears the value of the "related_order_no" field.
func (u *FinanceTransactionUpsertBulk) ClearRelatedOrderNo() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.ClearRelatedOrderNo()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *FinanceTransactionUpsertBulk) SetOperatorID(v uint32) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *FinanceTransactionUpsertBulk) AddOperatorID(v uint32) *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *FinanceTransactionUpsertBulk) UpdateOperatorID() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.UpdateOperatorID()
	})
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *FinanceTransactionUpsertBulk) ClearOperatorID() *FinanceTransactionUpsertBulk {
	return u.Update(func(s *FinanceTransactionUpsert) {
		s.ClearOperatorID()
	})
}

// Exec executes the query.
func (u *FinanceTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FinanceTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FinanceTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FinanceTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
