// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/freighttemplate"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// FreightTemplateUpdate is the builder for updating FreightTemplate entities.
type FreightTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *FreightTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FreightTemplateUpdate builder.
func (_u *FreightTemplateUpdate) Where(ps ...predicate.FreightTemplate) *FreightTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FreightTemplateUpdate) SetCreatedBy(v uint32) *FreightTemplateUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableCreatedBy(v *uint32) *FreightTemplateUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *FreightTemplateUpdate) AddCreatedBy(v int32) *FreightTemplateUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *FreightTemplateUpdate) ClearCreatedBy() *FreightTemplateUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FreightTemplateUpdate) SetUpdatedBy(v uint32) *FreightTemplateUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableUpdatedBy(v *uint32) *FreightTemplateUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FreightTemplateUpdate) AddUpdatedBy(v int32) *FreightTemplateUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FreightTemplateUpdate) ClearUpdatedBy() *FreightTemplateUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *FreightTemplateUpdate) SetDeletedBy(v uint32) *FreightTemplateUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableDeletedBy(v *uint32) *FreightTemplateUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *FreightTemplateUpdate) AddDeletedBy(v int32) *FreightTemplateUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *FreightTemplateUpdate) ClearDeletedBy() *FreightTemplateUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FreightTemplateUpdate) SetUpdatedAt(v time.Time) *FreightTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableUpdatedAt(v *time.Time) *FreightTemplateUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FreightTemplateUpdate) ClearUpdatedAt() *FreightTemplateUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FreightTemplateUpdate) SetDeletedAt(v time.Time) *FreightTemplateUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableDeletedAt(v *time.Time) *FreightTemplateUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FreightTemplateUpdate) ClearDeletedAt() *FreightTemplateUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *FreightTemplateUpdate) SetName(v string) *FreightTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableName(v *string) *FreightTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCalculationType sets the "calculation_type" field.
func (_u *FreightTemplateUpdate) SetCalculationType(v freighttemplate.CalculationType) *FreightTemplateUpdate {
	_u.mutation.SetCalculationType(v)
	return _u
}

// SetNillableCalculationType sets the "calculation_type" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableCalculationType(v *freighttemplate.CalculationType) *FreightTemplateUpdate {
	if v != nil {
		_u.SetCalculationType(*v)
	}
	return _u
}

// SetFirstWeight sets the "first_weight" field.
func (_u *FreightTemplateUpdate) SetFirstWeight(v string) *FreightTemplateUpdate {
	_u.mutation.SetFirstWeight(v)
	return _u
}

// SetNillableFirstWeight sets the "first_weight" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableFirstWeight(v *string) *FreightTemplateUpdate {
	if v != nil {
		_u.SetFirstWeight(*v)
	}
	return _u
}

// ClearFirstWeight clears the value of the "first_weight" field.
func (_u *FreightTemplateUpdate) ClearFirstWeight() *FreightTemplateUpdate {
	_u.mutation.ClearFirstWeight()
	return _u
}

// SetFirstPrice sets the "first_price" field.
func (_u *FreightTemplateUpdate) SetFirstPrice(v string) *FreightTemplateUpdate {
	_u.mutation.SetFirstPrice(v)
	return _u
}

// SetNillableFirstPrice sets the "first_price" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableFirstPrice(v *string) *FreightTemplateUpdate {
	if v != nil {
		_u.SetFirstPrice(*v)
	}
	return _u
}

// ClearFirstPrice clears the value of the "first_price" field.
func (_u *FreightTemplateUpdate) ClearFirstPrice() *FreightTemplateUpdate {
	_u.mutation.ClearFirstPrice()
	return _u
}

// SetAdditionalWeight sets the "additional_weight" field.
func (_u *FreightTemplateUpdate) SetAdditionalWeight(v string) *FreightTemplateUpdate {
	_u.mutation.SetAdditionalWeight(v)
	return _u
}

// SetNillableAdditionalWeight sets the "additional_weight" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableAdditionalWeight(v *string) *FreightTemplateUpdate {
	if v != nil {
		_u.SetAdditionalWeight(*v)
	}
	return _u
}

// ClearAdditionalWeight clears the value of the "additional_weight" field.
func (_u *FreightTemplateUpdate) ClearAdditionalWeight() *FreightTemplateUpdate {
	_u.mutation.ClearAdditionalWeight()
	return _u
}

// SetAdditionalPrice sets the "additional_price" field.
func (_u *FreightTemplateUpdate) SetAdditionalPrice(v string) *FreightTemplateUpdate {
	_u.mutation.SetAdditionalPrice(v)
	return _u
}

// SetNillableAdditionalPrice sets the "additional_price" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableAdditionalPrice(v *string) *FreightTemplateUpdate {
	if v != nil {
		_u.SetAdditionalPrice(*v)
	}
	return _u
}

// ClearAdditionalPrice clears the value of the "additional_price" field.
func (_u *FreightTemplateUpdate) ClearAdditionalPrice() *FreightTemplateUpdate {
	_u.mutation.ClearAdditionalPrice()
	return _u
}

// SetRegionRules sets the "region_rules" field.
func (_u *FreightTemplateUpdate) SetRegionRules(v []map[string]interface{}) *FreightTemplateUpdate {
	_u.mutation.SetRegionRules(v)
	return _u
}

// AppendRegionRules appends value to the "region_rules" field.
func (_u *FreightTemplateUpdate) AppendRegionRules(v []map[string]interface{}) *FreightTemplateUpdate {
	_u.mutation.AppendRegionRules(v)
	return _u
}

// ClearRegionRules clears the value of the "region_rules" field.
func (_u *FreightTemplateUpdate) ClearRegionRules() *FreightTemplateUpdate {
	_u.mutation.ClearRegionRules()
	return _u
}

// SetFreeShippingRules sets the "free_shipping_rules" field.
func (_u *FreightTemplateUpdate) SetFreeShippingRules(v []map[string]interface{}) *FreightTemplateUpdate {
	_u.mutation.SetFreeShippingRules(v)
	return _u
}

// AppendFreeShippingRules appends value to the "free_shipping_rules" field.
func (_u *FreightTemplateUpdate) AppendFreeShippingRules(v []map[string]interface{}) *FreightTemplateUpdate {
	_u.mutation.AppendFreeShippingRules(v)
	return _u
}

// ClearFreeShippingRules clears the value of the "free_shipping_rules" field.
func (_u *FreightTemplateUpdate) ClearFreeShippingRules() *FreightTemplateUpdate {
	_u.mutation.ClearFreeShippingRules()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *FreightTemplateUpdate) SetIsActive(v bool) *FreightTemplateUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *FreightTemplateUpdate) SetNillableIsActive(v *bool) *FreightTemplateUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the FreightTemplateMutation object of the builder.
func (_u *FreightTemplateUpdate) Mutation() *FreightTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FreightTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FreightTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FreightTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FreightTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FreightTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := freighttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CalculationType(); ok {
		if err := freighttemplate.CalculationTypeValidator(v); err != nil {
			return &ValidationError{Name: "calculation_type", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.calculation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstWeight(); ok {
		if err := freighttemplate.FirstWeightValidator(v); err != nil {
			return &ValidationError{Name: "first_weight", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.first_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstPrice(); ok {
		if err := freighttemplate.FirstPriceValidator(v); err != nil {
			return &ValidationError{Name: "first_price", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.first_price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdditionalWeight(); ok {
		if err := freighttemplate.AdditionalWeightValidator(v); err != nil {
			return &ValidationError{Name: "additional_weight", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.additional_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdditionalPrice(); ok {
		if err := freighttemplate.AdditionalPriceValidator(v); err != nil {
			return &ValidationError{Name: "additional_price", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.additional_price": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FreightTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FreightTemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FreightTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(freighttemplate.Table, freighttemplate.Columns, sqlgraph.NewFieldSpec(freighttemplate.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(freighttemplate.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(freighttemplate.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(freighttemplate.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(freighttemplate.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(freighttemplate.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(freighttemplate.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(freighttemplate.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(freighttemplate.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(freighttemplate.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(freighttemplate.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(freighttemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(freighttemplate.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(freighttemplate.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(freighttemplate.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(freighttemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(freighttemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalculationType(); ok {
		_spec.SetField(freighttemplate.FieldCalculationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FirstWeight(); ok {
		_spec.SetField(freighttemplate.FieldFirstWeight, field.TypeString, value)
	}
	if _u.mutation.FirstWeightCleared() {
		_spec.ClearField(freighttemplate.FieldFirstWeight, field.TypeString)
	}
	if value, ok := _u.mutation.FirstPrice(); ok {
		_spec.SetField(freighttemplate.FieldFirstPrice, field.TypeString, value)
	}
	if _u.mutation.FirstPriceCleared() {
		_spec.ClearField(freighttemplate.FieldFirstPrice, field.TypeString)
	}
	if value, ok := _u.mutation.AdditionalWeight(); ok {
		_spec.SetField(freighttemplate.FieldAdditionalWeight, field.TypeString, value)
	}
	if _u.mutation.AdditionalWeightCleared() {
		_spec.ClearField(freighttemplate.FieldAdditionalWeight, field.TypeString)
	}
	if value, ok := _u.mutation.AdditionalPrice(); ok {
		_spec.SetField(freighttemplate.FieldAdditionalPrice, field.TypeString, value)
	}
	if _u.mutation.AdditionalPriceCleared() {
		_spec.ClearField(freighttemplate.FieldAdditionalPrice, field.TypeString)
	}
	if value, ok := _u.mutation.RegionRules(); ok {
		_spec.SetField(freighttemplate.FieldRegionRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRegionRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, freighttemplate.FieldRegionRules, value)
		})
	}
	if _u.mutation.RegionRulesCleared() {
		_spec.ClearField(freighttemplate.FieldRegionRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.FreeShippingRules(); ok {
		_spec.SetField(freighttemplate.FieldFreeShippingRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFreeShippingRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, freighttemplate.FieldFreeShippingRules, value)
		})
	}
	if _u.mutation.FreeShippingRulesCleared() {
		_spec.ClearField(freighttemplate.FieldFreeShippingRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(freighttemplate.FieldIsActive, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{freighttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FreightTemplateUpdateOne is the builder for updating a single FreightTemplate entity.
type FreightTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FreightTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedBy sets the "created_by" field.
func (_u *FreightTemplateUpdateOne) SetCreatedBy(v uint32) *FreightTemplateUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableCreatedBy(v *uint32) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *FreightTemplateUpdateOne) AddCreatedBy(v int32) *FreightTemplateUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *FreightTemplateUpdateOne) ClearCreatedBy() *FreightTemplateUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FreightTemplateUpdateOne) SetUpdatedBy(v uint32) *FreightTemplateUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableUpdatedBy(v *uint32) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FreightTemplateUpdateOne) AddUpdatedBy(v int32) *FreightTemplateUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FreightTemplateUpdateOne) ClearUpdatedBy() *FreightTemplateUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *FreightTemplateUpdateOne) SetDeletedBy(v uint32) *FreightTemplateUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableDeletedBy(v *uint32) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *FreightTemplateUpdateOne) AddDeletedBy(v int32) *FreightTemplateUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *FreightTemplateUpdateOne) ClearDeletedBy() *FreightTemplateUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FreightTemplateUpdateOne) SetUpdatedAt(v time.Time) *FreightTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableUpdatedAt(v *time.Time) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FreightTemplateUpdateOne) ClearUpdatedAt() *FreightTemplateUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FreightTemplateUpdateOne) SetDeletedAt(v time.Time) *FreightTemplateUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableDeletedAt(v *time.Time) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FreightTemplateUpdateOne) ClearDeletedAt() *FreightTemplateUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *FreightTemplateUpdateOne) SetName(v string) *FreightTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableName(v *string) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCalculationType sets the "calculation_type" field.
func (_u *FreightTemplateUpdateOne) SetCalculationType(v freighttemplate.CalculationType) *FreightTemplateUpdateOne {
	_u.mutation.SetCalculationType(v)
	return _u
}

// SetNillableCalculationType sets the "calculation_type" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableCalculationType(v *freighttemplate.CalculationType) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetCalculationType(*v)
	}
	return _u
}

// SetFirstWeight sets the "first_weight" field.
func (_u *FreightTemplateUpdateOne) SetFirstWeight(v string) *FreightTemplateUpdateOne {
	_u.mutation.SetFirstWeight(v)
	return _u
}

// SetNillableFirstWeight sets the "first_weight" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableFirstWeight(v *string) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetFirstWeight(*v)
	}
	return _u
}

// ClearFirstWeight clears the value of the "first_weight" field.
func (_u *FreightTemplateUpdateOne) ClearFirstWeight() *FreightTemplateUpdateOne {
	_u.mutation.ClearFirstWeight()
	return _u
}

// SetFirstPrice sets the "first_price" field.
func (_u *FreightTemplateUpdateOne) SetFirstPrice(v string) *FreightTemplateUpdateOne {
	_u.mutation.SetFirstPrice(v)
	return _u
}

// SetNillableFirstPrice sets the "first_price" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableFirstPrice(v *string) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetFirstPrice(*v)
	}
	return _u
}

// ClearFirstPrice clears the value of the "first_price" field.
func (_u *FreightTemplateUpdateOne) ClearFirstPrice() *FreightTemplateUpdateOne {
	_u.mutation.ClearFirstPrice()
	return _u
}

// SetAdditionalWeight sets the "additional_weight" field.
func (_u *FreightTemplateUpdateOne) SetAdditionalWeight(v string) *FreightTemplateUpdateOne {
	_u.mutation.SetAdditionalWeight(v)
	return _u
}

// SetNillableAdditionalWeight sets the "additional_weight" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableAdditionalWeight(v *string) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetAdditionalWeight(*v)
	}
	return _u
}

// ClearAdditionalWeight clears the value of the "additional_weight" field.
func (_u *FreightTemplateUpdateOne) ClearAdditionalWeight() *FreightTemplateUpdateOne {
	_u.mutation.ClearAdditionalWeight()
	return _u
}

// SetAdditionalPrice sets the "additional_price" field.
func (_u *FreightTemplateUpdateOne) SetAdditionalPrice(v string) *FreightTemplateUpdateOne {
	_u.mutation.SetAdditionalPrice(v)
	return _u
}

// SetNillableAdditionalPrice sets the "additional_price" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableAdditionalPrice(v *string) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetAdditionalPrice(*v)
	}
	return _u
}

// ClearAdditionalPrice clears the value of the "additional_price" field.
func (_u *FreightTemplateUpdateOne) ClearAdditionalPrice() *FreightTemplateUpdateOne {
	_u.mutation.ClearAdditionalPrice()
	return _u
}

// SetRegionRules sets the "region_rules" field.
func (_u *FreightTemplateUpdateOne) SetRegionRules(v []map[string]interface{}) *FreightTemplateUpdateOne {
	_u.mutation.SetRegionRules(v)
	return _u
}

// AppendRegionRules appends value to the "region_rules" field.
func (_u *FreightTemplateUpdateOne) AppendRegionRules(v []map[string]interface{}) *FreightTemplateUpdateOne {
	_u.mutation.AppendRegionRules(v)
	return _u
}

// ClearRegionRules clears the value of the "region_rules" field.
func (_u *FreightTemplateUpdateOne) ClearRegionRules() *FreightTemplateUpdateOne {
	_u.mutation.ClearRegionRules()
	return _u
}

// SetFreeShippingRules sets the "free_shipping_rules" field.
func (_u *FreightTemplateUpdateOne) SetFreeShippingRules(v []map[string]interface{}) *FreightTemplateUpdateOne {
	_u.mutation.SetFreeShippingRules(v)
	return _u
}

// AppendFreeShippingRules appends value to the "free_shipping_rules" field.
func (_u *FreightTemplateUpdateOne) AppendFreeShippingRules(v []map[string]interface{}) *FreightTemplateUpdateOne {
	_u.mutation.AppendFreeShippingRules(v)
	return _u
}

// ClearFreeShippingRules clears the value of the "free_shipping_rules" field.
func (_u *FreightTemplateUpdateOne) ClearFreeShippingRules() *FreightTemplateUpdateOne {
	_u.mutation.ClearFreeShippingRules()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *FreightTemplateUpdateOne) SetIsActive(v bool) *FreightTemplateUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *FreightTemplateUpdateOne) SetNillableIsActive(v *bool) *FreightTemplateUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the FreightTemplateMutation object of the builder.
func (_u *FreightTemplateUpdateOne) Mutation() *FreightTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the FreightTemplateUpdate builder.
func (_u *FreightTemplateUpdateOne) Where(ps ...predicate.FreightTemplate) *FreightTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FreightTemplateUpdateOne) Select(field string, fields ...string) *FreightTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FreightTemplate entity.
func (_u *FreightTemplateUpdateOne) Save(ctx context.Context) (*FreightTemplate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FreightTemplateUpdateOne) SaveX(ctx context.Context) *FreightTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FreightTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FreightTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FreightTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := freighttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CalculationType(); ok {
		if err := freighttemplate.CalculationTypeValidator(v); err != nil {
			return &ValidationError{Name: "calculation_type", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.calculation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstWeight(); ok {
		if err := freighttemplate.FirstWeightValidator(v); err != nil {
			return &ValidationError{Name: "first_weight", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.first_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirstPrice(); ok {
		if err := freighttemplate.FirstPriceValidator(v); err != nil {
			return &ValidationError{Name: "first_price", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.first_price": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdditionalWeight(); ok {
		if err := freighttemplate.AdditionalWeightValidator(v); err != nil {
			return &ValidationError{Name: "additional_weight", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.additional_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdditionalPrice(); ok {
		if err := freighttemplate.AdditionalPriceValidator(v); err != nil {
			return &ValidationError{Name: "additional_price", err: fmt.Errorf(`ent: validator failed for field "FreightTemplate.additional_price": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FreightTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FreightTemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FreightTemplateUpdateOne) sqlSave(ctx context.Context) (_node *FreightTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(freighttemplate.Table, freighttemplate.Columns, sqlgraph.NewFieldSpec(freighttemplate.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FreightTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, freighttemplate.FieldID)
		for _, f := range fields {
			if !freighttemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != freighttemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(freighttemplate.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(freighttemplate.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(freighttemplate.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(freighttemplate.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(freighttemplate.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(freighttemplate.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(freighttemplate.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(freighttemplate.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(freighttemplate.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(freighttemplate.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(freighttemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(freighttemplate.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(freighttemplate.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(freighttemplate.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(freighttemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(freighttemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalculationType(); ok {
		_spec.SetField(freighttemplate.FieldCalculationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FirstWeight(); ok {
		_spec.SetField(freighttemplate.FieldFirstWeight, field.TypeString, value)
	}
	if _u.mutation.FirstWeightCleared() {
		_spec.ClearField(freighttemplate.FieldFirstWeight, field.TypeString)
	}
	if value, ok := _u.mutation.FirstPrice(); ok {
		_spec.SetField(freighttemplate.FieldFirstPrice, field.TypeString, value)
	}
	if _u.mutation.FirstPriceCleared() {
		_spec.ClearField(freighttemplate.FieldFirstPrice, field.TypeString)
	}
	if value, ok := _u.mutation.AdditionalWeight(); ok {
		_spec.SetField(freighttemplate.FieldAdditionalWeight, field.TypeString, value)
	}
	if _u.mutation.AdditionalWeightCleared() {
		_spec.ClearField(freighttemplate.FieldAdditionalWeight, field.TypeString)
	}
	if value, ok := _u.mutation.AdditionalPrice(); ok {
		_spec.SetField(freighttemplate.FieldAdditionalPrice, field.TypeString, value)
	}
	if _u.mutation.AdditionalPriceCleared() {
		_spec.ClearField(freighttemplate.FieldAdditionalPrice, field.TypeString)
	}
	if value, ok := _u.mutation.RegionRules(); ok {
		_spec.SetField(freighttemplate.FieldRegionRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRegionRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, freighttemplate.FieldRegionRules, value)
		})
	}
	if _u.mutation.RegionRulesCleared() {
		_spec.ClearField(freighttemplate.FieldRegionRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.FreeShippingRules(); ok {
		_spec.SetField(freighttemplate.FieldFreeShippingRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFreeShippingRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, freighttemplate.FieldFreeShippingRules, value)
		})
	}
	if _u.mutation.FreeShippingRulesCleared() {
		_spec.ClearField(freighttemplate.FieldFreeShippingRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(freighttemplate.FieldIsActive, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &FreightTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{freighttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
