// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-admin/app/consumer/service/internal/data/ent/logisticstracking"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogisticsTrackingDelete is the builder for deleting a LogisticsTracking entity.
type LogisticsTrackingDelete struct {
	config
	hooks    []Hook
	mutation *LogisticsTrackingMutation
}

// Where appends a list predicates to the LogisticsTrackingDelete builder.
func (_d *LogisticsTrackingDelete) Where(ps ...predicate.LogisticsTracking) *LogisticsTrackingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LogisticsTrackingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LogisticsTrackingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LogisticsTrackingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(logisticstracking.Table, sqlgraph.NewFieldSpec(logisticstracking.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LogisticsTrackingDeleteOne is the builder for deleting a single LogisticsTracking entity.
type LogisticsTrackingDeleteOne struct {
	_d *LogisticsTrackingDelete
}

// Where appends a list predicates to the LogisticsTrackingDelete builder.
func (_d *LogisticsTrackingDeleteOne) Where(ps ...predicate.LogisticsTracking) *LogisticsTrackingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LogisticsTrackingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{logisticstracking.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LogisticsTrackingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
