// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/loginlog"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginLogUpdate is the builder for updating LoginLog entities.
type LoginLogUpdate struct {
	config
	hooks    []Hook
	mutation *LoginLogMutation
}

// Where appends a list predicates to the LoginLogUpdate builder.
func (_u *LoginLogUpdate) Where(ps ...predicate.LoginLog) *LoginLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *LoginLogUpdate) SetConsumerID(v uint32) *LoginLogUpdate {
	_u.mutation.ResetConsumerID()
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableConsumerID(v *uint32) *LoginLogUpdate {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// AddConsumerID adds value to the "consumer_id" field.
func (_u *LoginLogUpdate) AddConsumerID(v int32) *LoginLogUpdate {
	_u.mutation.AddConsumerID(v)
	return _u
}

// SetPhone sets the "phone" field.
func (_u *LoginLogUpdate) SetPhone(v string) *LoginLogUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillablePhone(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetLoginType sets the "login_type" field.
func (_u *LoginLogUpdate) SetLoginType(v loginlog.LoginType) *LoginLogUpdate {
	_u.mutation.SetLoginType(v)
	return _u
}

// SetNillableLoginType sets the "login_type" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableLoginType(v *loginlog.LoginType) *LoginLogUpdate {
	if v != nil {
		_u.SetLoginType(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginLogUpdate) SetSuccess(v bool) *LoginLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableSuccess(v *bool) *LoginLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetFailReason sets the "fail_reason" field.
func (_u *LoginLogUpdate) SetFailReason(v string) *LoginLogUpdate {
	_u.mutation.SetFailReason(v)
	return _u
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableFailReason(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetFailReason(*v)
	}
	return _u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (_u *LoginLogUpdate) ClearFailReason() *LoginLogUpdate {
	_u.mutation.ClearFailReason()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *LoginLogUpdate) SetIPAddress(v string) *LoginLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableIPAddress(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginLogUpdate) SetUserAgent(v string) *LoginLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableUserAgent(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginLogUpdate) ClearUserAgent() *LoginLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *LoginLogUpdate) SetDeviceType(v string) *LoginLogUpdate {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableDeviceType(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// ClearDeviceType clears the value of the "device_type" field.
func (_u *LoginLogUpdate) ClearDeviceType() *LoginLogUpdate {
	_u.mutation.ClearDeviceType()
	return _u
}

// SetLoginAt sets the "login_at" field.
func (_u *LoginLogUpdate) SetLoginAt(v time.Time) *LoginLogUpdate {
	_u.mutation.SetLoginAt(v)
	return _u
}

// SetNillableLoginAt sets the "login_at" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableLoginAt(v *time.Time) *LoginLogUpdate {
	if v != nil {
		_u.SetLoginAt(*v)
	}
	return _u
}

// Mutation returns the LoginLogMutation object of the builder.
func (_u *LoginLogUpdate) Mutation() *LoginLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginLogUpdate) check() error {
	if v, ok := _u.mutation.Phone(); ok {
		if err := loginlog.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "LoginLog.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginType(); ok {
		if err := loginlog.LoginTypeValidator(v); err != nil {
			return &ValidationError{Name: "login_type", err: fmt.Errorf(`ent: validator failed for field "LoginLog.login_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailReason(); ok {
		if err := loginlog.FailReasonValidator(v); err != nil {
			return &ValidationError{Name: "fail_reason", err: fmt.Errorf(`ent: validator failed for field "LoginLog.fail_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := loginlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "LoginLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := loginlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "LoginLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := loginlog.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "LoginLog.device_type": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginlog.Table, loginlog.Columns, sqlgraph.NewFieldSpec(loginlog.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(loginlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConsumerID(); ok {
		_spec.SetField(loginlog.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedConsumerID(); ok {
		_spec.AddField(loginlog.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(loginlog.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.LoginType(); ok {
		_spec.SetField(loginlog.FieldLoginType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailReason(); ok {
		_spec.SetField(loginlog.FieldFailReason, field.TypeString, value)
	}
	if _u.mutation.FailReasonCleared() {
		_spec.ClearField(loginlog.FieldFailReason, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(loginlog.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(loginlog.FieldDeviceType, field.TypeString, value)
	}
	if _u.mutation.DeviceTypeCleared() {
		_spec.ClearField(loginlog.FieldDeviceType, field.TypeString)
	}
	if value, ok := _u.mutation.LoginAt(); ok {
		_spec.SetField(loginlog.FieldLoginAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginLogUpdateOne is the builder for updating a single LoginLog entity.
type LoginLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginLogMutation
}

// SetConsumerID sets the "consumer_id" field.
func (_u *LoginLogUpdateOne) SetConsumerID(v uint32) *LoginLogUpdateOne {
	_u.mutation.ResetConsumerID()
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableConsumerID(v *uint32) *LoginLogUpdateOne {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// AddConsumerID adds value to the "consumer_id" field.
func (_u *LoginLogUpdateOne) AddConsumerID(v int32) *LoginLogUpdateOne {
	_u.mutation.AddConsumerID(v)
	return _u
}

// SetPhone sets the "phone" field.
func (_u *LoginLogUpdateOne) SetPhone(v string) *LoginLogUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillablePhone(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetLoginType sets the "login_type" field.
func (_u *LoginLogUpdateOne) SetLoginType(v loginlog.LoginType) *LoginLogUpdateOne {
	_u.mutation.SetLoginType(v)
	return _u
}

// SetNillableLoginType sets the "login_type" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableLoginType(v *loginlog.LoginType) *LoginLogUpdateOne {
	if v != nil {
		_u.SetLoginType(*v)
	}
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginLogUpdateOne) SetSuccess(v bool) *LoginLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableSuccess(v *bool) *LoginLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetFailReason sets the "fail_reason" field.
func (_u *LoginLogUpdateOne) SetFailReason(v string) *LoginLogUpdateOne {
	_u.mutation.SetFailReason(v)
	return _u
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableFailReason(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetFailReason(*v)
	}
	return _u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (_u *LoginLogUpdateOne) ClearFailReason() *LoginLogUpdateOne {
	_u.mutation.ClearFailReason()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *LoginLogUpdateOne) SetIPAddress(v string) *LoginLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableIPAddress(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginLogUpdateOne) SetUserAgent(v string) *LoginLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableUserAgent(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginLogUpdateOne) ClearUserAgent() *LoginLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *LoginLogUpdateOne) SetDeviceType(v string) *LoginLogUpdateOne {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableDeviceType(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// ClearDeviceType clears the value of the "device_type" field.
func (_u *LoginLogUpdateOne) ClearDeviceType() *LoginLogUpdateOne {
	_u.mutation.ClearDeviceType()
	return _u
}

// SetLoginAt sets the "login_at" field.
func (_u *LoginLogUpdateOne) SetLoginAt(v time.Time) *LoginLogUpdateOne {
	_u.mutation.SetLoginAt(v)
	return _u
}

// SetNillableLoginAt sets the "login_at" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableLoginAt(v *time.Time) *LoginLogUpdateOne {
	if v != nil {
		_u.SetLoginAt(*v)
	}
	return _u
}

// Mutation returns the LoginLogMutation object of the builder.
func (_u *LoginLogUpdateOne) Mutation() *LoginLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginLogUpdate builder.
func (_u *LoginLogUpdateOne) Where(ps ...predicate.LoginLog) *LoginLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginLogUpdateOne) Select(field string, fields ...string) *LoginLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginLog entity.
func (_u *LoginLogUpdateOne) Save(ctx context.Context) (*LoginLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginLogUpdateOne) SaveX(ctx context.Context) *LoginLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginLogUpdateOne) check() error {
	if v, ok := _u.mutation.Phone(); ok {
		if err := loginlog.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "LoginLog.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginType(); ok {
		if err := loginlog.LoginTypeValidator(v); err != nil {
			return &ValidationError{Name: "login_type", err: fmt.Errorf(`ent: validator failed for field "LoginLog.login_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailReason(); ok {
		if err := loginlog.FailReasonValidator(v); err != nil {
			return &ValidationError{Name: "fail_reason", err: fmt.Errorf(`ent: validator failed for field "LoginLog.fail_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := loginlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "LoginLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := loginlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "LoginLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceType(); ok {
		if err := loginlog.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "LoginLog.device_type": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginLogUpdateOne) sqlSave(ctx context.Context) (_node *LoginLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginlog.Table, loginlog.Columns, sqlgraph.NewFieldSpec(loginlog.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginlog.FieldID)
		for _, f := range fields {
			if !loginlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(loginlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConsumerID(); ok {
		_spec.SetField(loginlog.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedConsumerID(); ok {
		_spec.AddField(loginlog.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(loginlog.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.LoginType(); ok {
		_spec.SetField(loginlog.FieldLoginType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailReason(); ok {
		_spec.SetField(loginlog.FieldFailReason, field.TypeString, value)
	}
	if _u.mutation.FailReasonCleared() {
		_spec.ClearField(loginlog.FieldFailReason, field.TypeString)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(loginlog.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(loginlog.FieldDeviceType, field.TypeString, value)
	}
	if _u.mutation.DeviceTypeCleared() {
		_spec.ClearField(loginlog.FieldDeviceType, field.TypeString)
	}
	if value, ok := _u.mutation.LoginAt(); ok {
		_spec.SetField(loginlog.FieldLoginAt, field.TypeTime, value)
	}
	_node = &LoginLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
