// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/loginlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginLogCreate is the builder for creating a LoginLog entity.
type LoginLogCreate struct {
	config
	mutation *LoginLogMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *LoginLogCreate) SetTenantID(v uint32) *LoginLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableTenantID(v *uint32) *LoginLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetConsumerID sets the "consumer_id" field.
func (_c *LoginLogCreate) SetConsumerID(v uint32) *LoginLogCreate {
	_c.mutation.SetConsumerID(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *LoginLogCreate) SetPhone(v string) *LoginLogCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetLoginType sets the "login_type" field.
func (_c *LoginLogCreate) SetLoginType(v loginlog.LoginType) *LoginLogCreate {
	_c.mutation.SetLoginType(v)
	return _c
}

// SetSuccess sets the "success" field.
func (_c *LoginLogCreate) SetSuccess(v bool) *LoginLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableSuccess(v *bool) *LoginLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetFailReason sets the "fail_reason" field.
func (_c *LoginLogCreate) SetFailReason(v string) *LoginLogCreate {
	_c.mutation.SetFailReason(v)
	return _c
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableFailReason(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetFailReason(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *LoginLogCreate) SetIPAddress(v string) *LoginLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *LoginLogCreate) SetUserAgent(v string) *LoginLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableUserAgent(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetDeviceType sets the "device_type" field.
func (_c *LoginLogCreate) SetDeviceType(v string) *LoginLogCreate {
	_c.mutation.SetDeviceType(v)
	return _c
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableDeviceType(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetDeviceType(*v)
	}
	return _c
}

// SetLoginAt sets the "login_at" field.
func (_c *LoginLogCreate) SetLoginAt(v time.Time) *LoginLogCreate {
	_c.mutation.SetLoginAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *LoginLogCreate) SetID(v uint32) *LoginLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LoginLogMutation object of the builder.
func (_c *LoginLogCreate) Mutation() *LoginLogMutation {
	return _c.mutation
}

// Save creates the LoginLog in the database.
func (_c *LoginLogCreate) Save(ctx context.Context) (*LoginLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoginLogCreate) SaveX(ctx context.Context) *LoginLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoginLogCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := loginlog.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := loginlog.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoginLogCreate) check() error {
	if _, ok := _c.mutation.ConsumerID(); !ok {
		return &ValidationError{Name: "consumer_id", err: errors.New(`ent: missing required field "LoginLog.consumer_id"`)}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "LoginLog.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := loginlog.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "LoginLog.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginType(); !ok {
		return &ValidationError{Name: "login_type", err: errors.New(`ent: missing required field "LoginLog.login_type"`)}
	}
	if v, ok := _c.mutation.LoginType(); ok {
		if err := loginlog.LoginTypeValidator(v); err != nil {
			return &ValidationError{Name: "login_type", err: fmt.Errorf(`ent: validator failed for field "LoginLog.login_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "LoginLog.success"`)}
	}
	if v, ok := _c.mutation.FailReason(); ok {
		if err := loginlog.FailReasonValidator(v); err != nil {
			return &ValidationError{Name: "fail_reason", err: fmt.Errorf(`ent: validator failed for field "LoginLog.fail_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "LoginLog.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := loginlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "LoginLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := loginlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "LoginLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceType(); ok {
		if err := loginlog.DeviceTypeValidator(v); err != nil {
			return &ValidationError{Name: "device_type", err: fmt.Errorf(`ent: validator failed for field "LoginLog.device_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginAt(); !ok {
		return &ValidationError{Name: "login_at", err: errors.New(`ent: missing required field "LoginLog.login_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := loginlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "LoginLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *LoginLogCreate) sqlSave(ctx context.Context) (*LoginLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoginLogCreate) createSpec() (*LoginLog, *sqlgraph.CreateSpec) {
	var (
		_node = &LoginLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loginlog.Table, sqlgraph.NewFieldSpec(loginlog.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(loginlog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ConsumerID(); ok {
		_spec.SetField(loginlog.FieldConsumerID, field.TypeUint32, value)
		_node.ConsumerID = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(loginlog.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.LoginType(); ok {
		_spec.SetField(loginlog.FieldLoginType, field.TypeEnum, value)
		_node.LoginType = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(loginlog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.FailReason(); ok {
		_spec.SetField(loginlog.FieldFailReason, field.TypeString, value)
		_node.FailReason = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(loginlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(loginlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.DeviceType(); ok {
		_spec.SetField(loginlog.FieldDeviceType, field.TypeString, value)
		_node.DeviceType = &value
	}
	if value, ok := _c.mutation.LoginAt(); ok {
		_spec.SetField(loginlog.FieldLoginAt, field.TypeTime, value)
		_node.LoginAt = value
	}
	return _node, _spec
}

// LoginLogCreateBulk is the builder for creating many LoginLog entities in bulk.
type LoginLogCreateBulk struct {
	config
	err      error
	builders []*LoginLogCreate
}

// Save creates the LoginLog entities in the database.
func (_c *LoginLogCreateBulk) Save(ctx context.Context) ([]*LoginLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoginLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoginLogCreateBulk) SaveX(ctx context.Context) []*LoginLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
