// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/mediafile"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaFileUpdate is the builder for updating MediaFile entities.
type MediaFileUpdate struct {
	config
	hooks    []Hook
	mutation *MediaFileMutation
}

// Where appends a list predicates to the MediaFileUpdate builder.
func (_u *MediaFileUpdate) Where(ps ...predicate.MediaFile) *MediaFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *MediaFileUpdate) SetCreatedBy(v uint32) *MediaFileUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableCreatedBy(v *uint32) *MediaFileUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *MediaFileUpdate) AddCreatedBy(v int32) *MediaFileUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *MediaFileUpdate) ClearCreatedBy() *MediaFileUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *MediaFileUpdate) SetUpdatedBy(v uint32) *MediaFileUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableUpdatedBy(v *uint32) *MediaFileUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *MediaFileUpdate) AddUpdatedBy(v int32) *MediaFileUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *MediaFileUpdate) ClearUpdatedBy() *MediaFileUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *MediaFileUpdate) SetDeletedBy(v uint32) *MediaFileUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableDeletedBy(v *uint32) *MediaFileUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *MediaFileUpdate) AddDeletedBy(v int32) *MediaFileUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *MediaFileUpdate) ClearDeletedBy() *MediaFileUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaFileUpdate) SetUpdatedAt(v time.Time) *MediaFileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableUpdatedAt(v *time.Time) *MediaFileUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MediaFileUpdate) ClearUpdatedAt() *MediaFileUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MediaFileUpdate) SetDeletedAt(v time.Time) *MediaFileUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableDeletedAt(v *time.Time) *MediaFileUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MediaFileUpdate) ClearDeletedAt() *MediaFileUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *MediaFileUpdate) SetConsumerID(v uint32) *MediaFileUpdate {
	_u.mutation.ResetConsumerID()
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableConsumerID(v *uint32) *MediaFileUpdate {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// AddConsumerID adds value to the "consumer_id" field.
func (_u *MediaFileUpdate) AddConsumerID(v int32) *MediaFileUpdate {
	_u.mutation.AddConsumerID(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *MediaFileUpdate) SetFileName(v string) *MediaFileUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableFileName(v *string) *MediaFileUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *MediaFileUpdate) SetFileType(v mediafile.FileType) *MediaFileUpdate {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableFileType(v *mediafile.FileType) *MediaFileUpdate {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetFileFormat sets the "file_format" field.
func (_u *MediaFileUpdate) SetFileFormat(v string) *MediaFileUpdate {
	_u.mutation.SetFileFormat(v)
	return _u
}

// SetNillableFileFormat sets the "file_format" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableFileFormat(v *string) *MediaFileUpdate {
	if v != nil {
		_u.SetFileFormat(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *MediaFileUpdate) SetFileSize(v uint64) *MediaFileUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableFileSize(v *uint64) *MediaFileUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *MediaFileUpdate) AddFileSize(v int64) *MediaFileUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *MediaFileUpdate) SetFileURL(v string) *MediaFileUpdate {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableFileURL(v *string) *MediaFileUpdate {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *MediaFileUpdate) SetThumbnailURL(v string) *MediaFileUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableThumbnailURL(v *string) *MediaFileUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *MediaFileUpdate) ClearThumbnailURL() *MediaFileUpdate {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetOssBucket sets the "oss_bucket" field.
func (_u *MediaFileUpdate) SetOssBucket(v string) *MediaFileUpdate {
	_u.mutation.SetOssBucket(v)
	return _u
}

// SetNillableOssBucket sets the "oss_bucket" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableOssBucket(v *string) *MediaFileUpdate {
	if v != nil {
		_u.SetOssBucket(*v)
	}
	return _u
}

// SetOssKey sets the "oss_key" field.
func (_u *MediaFileUpdate) SetOssKey(v string) *MediaFileUpdate {
	_u.mutation.SetOssKey(v)
	return _u
}

// SetNillableOssKey sets the "oss_key" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableOssKey(v *string) *MediaFileUpdate {
	if v != nil {
		_u.SetOssKey(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *MediaFileUpdate) SetIsDeleted(v bool) *MediaFileUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *MediaFileUpdate) SetNillableIsDeleted(v *bool) *MediaFileUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// Mutation returns the MediaFileMutation object of the builder.
func (_u *MediaFileUpdate) Mutation() *MediaFileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaFileUpdate) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := mediafile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := mediafile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileFormat(); ok {
		if err := mediafile.FileFormatValidator(v); err != nil {
			return &ValidationError{Name: "file_format", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := mediafile.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThumbnailURL(); ok {
		if err := mediafile.ThumbnailURLValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_url", err: fmt.Errorf(`ent: validator failed for field "MediaFile.thumbnail_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OssBucket(); ok {
		if err := mediafile.OssBucketValidator(v); err != nil {
			return &ValidationError{Name: "oss_bucket", err: fmt.Errorf(`ent: validator failed for field "MediaFile.oss_bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OssKey(); ok {
		if err := mediafile.OssKeyValidator(v); err != nil {
			return &ValidationError{Name: "oss_key", err: fmt.Errorf(`ent: validator failed for field "MediaFile.oss_key": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediafile.Table, mediafile.Columns, sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(mediafile.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(mediafile.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(mediafile.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(mediafile.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(mediafile.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(mediafile.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(mediafile.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(mediafile.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(mediafile.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(mediafile.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediafile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(mediafile.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mediafile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mediafile.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(mediafile.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConsumerID(); ok {
		_spec.SetField(mediafile.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedConsumerID(); ok {
		_spec.AddField(mediafile.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(mediafile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(mediafile.FieldFileType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FileFormat(); ok {
		_spec.SetField(mediafile.FieldFileFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(mediafile.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(mediafile.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(mediafile.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediafile.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(mediafile.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.OssBucket(); ok {
		_spec.SetField(mediafile.FieldOssBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.OssKey(); ok {
		_spec.SetField(mediafile.FieldOssKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(mediafile.FieldIsDeleted, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediafile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaFileUpdateOne is the builder for updating a single MediaFile entity.
type MediaFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaFileMutation
}

// SetCreatedBy sets the "created_by" field.
func (_u *MediaFileUpdateOne) SetCreatedBy(v uint32) *MediaFileUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableCreatedBy(v *uint32) *MediaFileUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *MediaFileUpdateOne) AddCreatedBy(v int32) *MediaFileUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *MediaFileUpdateOne) ClearCreatedBy() *MediaFileUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *MediaFileUpdateOne) SetUpdatedBy(v uint32) *MediaFileUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableUpdatedBy(v *uint32) *MediaFileUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *MediaFileUpdateOne) AddUpdatedBy(v int32) *MediaFileUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *MediaFileUpdateOne) ClearUpdatedBy() *MediaFileUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *MediaFileUpdateOne) SetDeletedBy(v uint32) *MediaFileUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableDeletedBy(v *uint32) *MediaFileUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *MediaFileUpdateOne) AddDeletedBy(v int32) *MediaFileUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *MediaFileUpdateOne) ClearDeletedBy() *MediaFileUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaFileUpdateOne) SetUpdatedAt(v time.Time) *MediaFileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableUpdatedAt(v *time.Time) *MediaFileUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *MediaFileUpdateOne) ClearUpdatedAt() *MediaFileUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MediaFileUpdateOne) SetDeletedAt(v time.Time) *MediaFileUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableDeletedAt(v *time.Time) *MediaFileUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MediaFileUpdateOne) ClearDeletedAt() *MediaFileUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetConsumerID sets the "consumer_id" field.
func (_u *MediaFileUpdateOne) SetConsumerID(v uint32) *MediaFileUpdateOne {
	_u.mutation.ResetConsumerID()
	_u.mutation.SetConsumerID(v)
	return _u
}

// SetNillableConsumerID sets the "consumer_id" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableConsumerID(v *uint32) *MediaFileUpdateOne {
	if v != nil {
		_u.SetConsumerID(*v)
	}
	return _u
}

// AddConsumerID adds value to the "consumer_id" field.
func (_u *MediaFileUpdateOne) AddConsumerID(v int32) *MediaFileUpdateOne {
	_u.mutation.AddConsumerID(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *MediaFileUpdateOne) SetFileName(v string) *MediaFileUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableFileName(v *string) *MediaFileUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *MediaFileUpdateOne) SetFileType(v mediafile.FileType) *MediaFileUpdateOne {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableFileType(v *mediafile.FileType) *MediaFileUpdateOne {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetFileFormat sets the "file_format" field.
func (_u *MediaFileUpdateOne) SetFileFormat(v string) *MediaFileUpdateOne {
	_u.mutation.SetFileFormat(v)
	return _u
}

// SetNillableFileFormat sets the "file_format" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableFileFormat(v *string) *MediaFileUpdateOne {
	if v != nil {
		_u.SetFileFormat(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *MediaFileUpdateOne) SetFileSize(v uint64) *MediaFileUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableFileSize(v *uint64) *MediaFileUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *MediaFileUpdateOne) AddFileSize(v int64) *MediaFileUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *MediaFileUpdateOne) SetFileURL(v string) *MediaFileUpdateOne {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableFileURL(v *string) *MediaFileUpdateOne {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *MediaFileUpdateOne) SetThumbnailURL(v string) *MediaFileUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableThumbnailURL(v *string) *MediaFileUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *MediaFileUpdateOne) ClearThumbnailURL() *MediaFileUpdateOne {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetOssBucket sets the "oss_bucket" field.
func (_u *MediaFileUpdateOne) SetOssBucket(v string) *MediaFileUpdateOne {
	_u.mutation.SetOssBucket(v)
	return _u
}

// SetNillableOssBucket sets the "oss_bucket" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableOssBucket(v *string) *MediaFileUpdateOne {
	if v != nil {
		_u.SetOssBucket(*v)
	}
	return _u
}

// SetOssKey sets the "oss_key" field.
func (_u *MediaFileUpdateOne) SetOssKey(v string) *MediaFileUpdateOne {
	_u.mutation.SetOssKey(v)
	return _u
}

// SetNillableOssKey sets the "oss_key" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableOssKey(v *string) *MediaFileUpdateOne {
	if v != nil {
		_u.SetOssKey(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *MediaFileUpdateOne) SetIsDeleted(v bool) *MediaFileUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *MediaFileUpdateOne) SetNillableIsDeleted(v *bool) *MediaFileUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// Mutation returns the MediaFileMutation object of the builder.
func (_u *MediaFileUpdateOne) Mutation() *MediaFileMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaFileUpdate builder.
func (_u *MediaFileUpdateOne) Where(ps ...predicate.MediaFile) *MediaFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaFileUpdateOne) Select(field string, fields ...string) *MediaFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaFile entity.
func (_u *MediaFileUpdateOne) Save(ctx context.Context) (*MediaFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaFileUpdateOne) SaveX(ctx context.Context) *MediaFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaFileUpdateOne) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := mediafile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := mediafile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileFormat(); ok {
		if err := mediafile.FileFormatValidator(v); err != nil {
			return &ValidationError{Name: "file_format", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileURL(); ok {
		if err := mediafile.FileURLValidator(v); err != nil {
			return &ValidationError{Name: "file_url", err: fmt.Errorf(`ent: validator failed for field "MediaFile.file_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThumbnailURL(); ok {
		if err := mediafile.ThumbnailURLValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_url", err: fmt.Errorf(`ent: validator failed for field "MediaFile.thumbnail_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OssBucket(); ok {
		if err := mediafile.OssBucketValidator(v); err != nil {
			return &ValidationError{Name: "oss_bucket", err: fmt.Errorf(`ent: validator failed for field "MediaFile.oss_bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OssKey(); ok {
		if err := mediafile.OssKeyValidator(v); err != nil {
			return &ValidationError{Name: "oss_key", err: fmt.Errorf(`ent: validator failed for field "MediaFile.oss_key": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaFileUpdateOne) sqlSave(ctx context.Context) (_node *MediaFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediafile.Table, mediafile.Columns, sqlgraph.NewFieldSpec(mediafile.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediafile.FieldID)
		for _, f := range fields {
			if !mediafile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediafile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(mediafile.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(mediafile.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(mediafile.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(mediafile.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(mediafile.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(mediafile.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(mediafile.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(mediafile.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(mediafile.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(mediafile.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediafile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(mediafile.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mediafile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mediafile.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(mediafile.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConsumerID(); ok {
		_spec.SetField(mediafile.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedConsumerID(); ok {
		_spec.AddField(mediafile.FieldConsumerID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(mediafile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(mediafile.FieldFileType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FileFormat(); ok {
		_spec.SetField(mediafile.FieldFileFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(mediafile.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(mediafile.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(mediafile.FieldFileURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediafile.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(mediafile.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.OssBucket(); ok {
		_spec.SetField(mediafile.FieldOssBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.OssKey(); ok {
		_spec.SetField(mediafile.FieldOssKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(mediafile.FieldIsDeleted, field.TypeBool, value)
	}
	_node = &MediaFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediafile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
