// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/paymentorder"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 支付订单表
type PaymentOrder struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 订单号
	OrderNo string `json:"order_no,omitempty"`
	// 用户ID
	ConsumerID uint32 `json:"consumer_id,omitempty"`
	// 支付方式
	PaymentMethod paymentorder.PaymentMethod `json:"payment_method,omitempty"`
	// 支付类型
	PaymentType paymentorder.PaymentType `json:"payment_type,omitempty"`
	// 支付金额（decimal字符串）
	Amount string `json:"amount,omitempty"`
	// 订单状态
	Status paymentorder.Status `json:"status,omitempty"`
	// 第三方交易号
	TransactionID *string `json:"transaction_id,omitempty"`
	// 回调数据
	CallbackData *string `json:"callback_data,omitempty"`
	// 支付时间
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// 关闭时间
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// 过期时间
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldID, paymentorder.FieldTenantID, paymentorder.FieldConsumerID:
			values[i] = new(sql.NullInt64)
		case paymentorder.FieldOrderNo, paymentorder.FieldPaymentMethod, paymentorder.FieldPaymentType, paymentorder.FieldAmount, paymentorder.FieldStatus, paymentorder.FieldTransactionID, paymentorder.FieldCallbackData:
			values[i] = new(sql.NullString)
		case paymentorder.FieldCreatedAt, paymentorder.FieldUpdatedAt, paymentorder.FieldDeletedAt, paymentorder.FieldPaidAt, paymentorder.FieldClosedAt, paymentorder.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentOrder fields.
func (_m *PaymentOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case paymentorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case paymentorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case paymentorder.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case paymentorder.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case paymentorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case paymentorder.FieldConsumerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_id", values[i])
			} else if value.Valid {
				_m.ConsumerID = uint32(value.Int64)
			}
		case paymentorder.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = paymentorder.PaymentMethod(value.String)
			}
		case paymentorder.FieldPaymentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_type", values[i])
			} else if value.Valid {
				_m.PaymentType = paymentorder.PaymentType(value.String)
			}
		case paymentorder.FieldAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.String
			}
		case paymentorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = paymentorder.Status(value.String)
			}
		case paymentorder.FieldTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_id", values[i])
			} else if value.Valid {
				_m.TransactionID = new(string)
				*_m.TransactionID = value.String
			}
		case paymentorder.FieldCallbackData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_data", values[i])
			} else if value.Valid {
				_m.CallbackData = new(string)
				*_m.CallbackData = value.String
			}
		case paymentorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case paymentorder.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case paymentorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentOrder.
// Note that you need to call PaymentOrder.Unwrap() before calling this method if this PaymentOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentOrder) Update() *PaymentOrderUpdateOne {
	return NewPaymentOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentOrder) Unwrap() *PaymentOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("consumer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumerID))
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentMethod))
	builder.WriteString(", ")
	builder.WriteString("payment_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentType))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(_m.Amount)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.TransactionID; v != nil {
		builder.WriteString("transaction_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CallbackData; v != nil {
		builder.WriteString("callback_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentOrders is a parsable slice of PaymentOrder.
type PaymentOrders []*PaymentOrder
