// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/smslog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SMSLogCreate is the builder for creating a SMSLog entity.
type SMSLogCreate struct {
	config
	mutation *SMSLogMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *SMSLogCreate) SetTenantID(v uint32) *SMSLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SMSLogCreate) SetNillableTenantID(v *uint32) *SMSLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *SMSLogCreate) SetPhone(v string) *SMSLogCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetSmsType sets the "sms_type" field.
func (_c *SMSLogCreate) SetSmsType(v smslog.SmsType) *SMSLogCreate {
	_c.mutation.SetSmsType(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SMSLogCreate) SetContent(v string) *SMSLogCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *SMSLogCreate) SetCode(v string) *SMSLogCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *SMSLogCreate) SetNillableCode(v *string) *SMSLogCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *SMSLogCreate) SetChannel(v smslog.Channel) *SMSLogCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SMSLogCreate) SetStatus(v smslog.Status) *SMSLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SMSLogCreate) SetNillableStatus(v *smslog.Status) *SMSLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SMSLogCreate) SetErrorMessage(v string) *SMSLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SMSLogCreate) SetNillableErrorMessage(v *string) *SMSLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *SMSLogCreate) SetSentAt(v time.Time) *SMSLogCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SMSLogCreate) SetExpiresAt(v time.Time) *SMSLogCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SMSLogCreate) SetNillableExpiresAt(v *time.Time) *SMSLogCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SMSLogCreate) SetID(v uint32) *SMSLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SMSLogMutation object of the builder.
func (_c *SMSLogCreate) Mutation() *SMSLogMutation {
	return _c.mutation
}

// Save creates the SMSLog in the database.
func (_c *SMSLogCreate) Save(ctx context.Context) (*SMSLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SMSLogCreate) SaveX(ctx context.Context) *SMSLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SMSLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SMSLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SMSLogCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := smslog.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := smslog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SMSLogCreate) check() error {
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "SMSLog.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := smslog.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SMSLog.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SmsType(); !ok {
		return &ValidationError{Name: "sms_type", err: errors.New(`ent: missing required field "SMSLog.sms_type"`)}
	}
	if v, ok := _c.mutation.SmsType(); ok {
		if err := smslog.SmsTypeValidator(v); err != nil {
			return &ValidationError{Name: "sms_type", err: fmt.Errorf(`ent: validator failed for field "SMSLog.sms_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SMSLog.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := smslog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SMSLog.content": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := smslog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SMSLog.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "SMSLog.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := smslog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "SMSLog.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SMSLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := smslog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SMSLog.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := smslog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "SMSLog.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "SMSLog.sent_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := smslog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SMSLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SMSLogCreate) sqlSave(ctx context.Context) (*SMSLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SMSLogCreate) createSpec() (*SMSLog, *sqlgraph.CreateSpec) {
	var (
		_node = &SMSLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(smslog.Table, sqlgraph.NewFieldSpec(smslog.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(smslog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(smslog.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.SmsType(); ok {
		_spec.SetField(smslog.FieldSmsType, field.TypeEnum, value)
		_node.SmsType = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(smslog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(smslog.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(smslog.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(smslog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(smslog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(smslog.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(smslog.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// SMSLogCreateBulk is the builder for creating many SMSLog entities in bulk.
type SMSLogCreateBulk struct {
	config
	err      error
	builders []*SMSLogCreate
}

// Save creates the SMSLog entities in the database.
func (_c *SMSLogCreateBulk) Save(ctx context.Context) ([]*SMSLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SMSLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SMSLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SMSLogCreateBulk) SaveX(ctx context.Context) []*SMSLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SMSLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SMSLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
