// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"go-wind-admin/app/consumer/service/internal/data/ent/smslog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SMSLogUpdate is the builder for updating SMSLog entities.
type SMSLogUpdate struct {
	config
	hooks    []Hook
	mutation *SMSLogMutation
}

// Where appends a list predicates to the SMSLogUpdate builder.
func (_u *SMSLogUpdate) Where(ps ...predicate.SMSLog) *SMSLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPhone sets the "phone" field.
func (_u *SMSLogUpdate) SetPhone(v string) *SMSLogUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillablePhone(v *string) *SMSLogUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetSmsType sets the "sms_type" field.
func (_u *SMSLogUpdate) SetSmsType(v smslog.SmsType) *SMSLogUpdate {
	_u.mutation.SetSmsType(v)
	return _u
}

// SetNillableSmsType sets the "sms_type" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableSmsType(v *smslog.SmsType) *SMSLogUpdate {
	if v != nil {
		_u.SetSmsType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SMSLogUpdate) SetContent(v string) *SMSLogUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableContent(v *string) *SMSLogUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SMSLogUpdate) SetCode(v string) *SMSLogUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableCode(v *string) *SMSLogUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *SMSLogUpdate) ClearCode() *SMSLogUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *SMSLogUpdate) SetChannel(v smslog.Channel) *SMSLogUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableChannel(v *smslog.Channel) *SMSLogUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SMSLogUpdate) SetStatus(v smslog.Status) *SMSLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableStatus(v *smslog.Status) *SMSLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SMSLogUpdate) SetErrorMessage(v string) *SMSLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableErrorMessage(v *string) *SMSLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SMSLogUpdate) ClearErrorMessage() *SMSLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *SMSLogUpdate) SetSentAt(v time.Time) *SMSLogUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableSentAt(v *time.Time) *SMSLogUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SMSLogUpdate) SetExpiresAt(v time.Time) *SMSLogUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SMSLogUpdate) SetNillableExpiresAt(v *time.Time) *SMSLogUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SMSLogUpdate) ClearExpiresAt() *SMSLogUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the SMSLogMutation object of the builder.
func (_u *SMSLogUpdate) Mutation() *SMSLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SMSLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SMSLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SMSLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SMSLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SMSLogUpdate) check() error {
	if v, ok := _u.mutation.Phone(); ok {
		if err := smslog.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SMSLog.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SmsType(); ok {
		if err := smslog.SmsTypeValidator(v); err != nil {
			return &ValidationError{Name: "sms_type", err: fmt.Errorf(`ent: validator failed for field "SMSLog.sms_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := smslog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SMSLog.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := smslog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SMSLog.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := smslog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "SMSLog.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := smslog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SMSLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := smslog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "SMSLog.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *SMSLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(smslog.Table, smslog.Columns, sqlgraph.NewFieldSpec(smslog.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(smslog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(smslog.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.SmsType(); ok {
		_spec.SetField(smslog.FieldSmsType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(smslog.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(smslog.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(smslog.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(smslog.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(smslog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(smslog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(smslog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(smslog.FieldSentAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(smslog.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(smslog.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{smslog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SMSLogUpdateOne is the builder for updating a single SMSLog entity.
type SMSLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SMSLogMutation
}

// SetPhone sets the "phone" field.
func (_u *SMSLogUpdateOne) SetPhone(v string) *SMSLogUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillablePhone(v *string) *SMSLogUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetSmsType sets the "sms_type" field.
func (_u *SMSLogUpdateOne) SetSmsType(v smslog.SmsType) *SMSLogUpdateOne {
	_u.mutation.SetSmsType(v)
	return _u
}

// SetNillableSmsType sets the "sms_type" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableSmsType(v *smslog.SmsType) *SMSLogUpdateOne {
	if v != nil {
		_u.SetSmsType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SMSLogUpdateOne) SetContent(v string) *SMSLogUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableContent(v *string) *SMSLogUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SMSLogUpdateOne) SetCode(v string) *SMSLogUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableCode(v *string) *SMSLogUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *SMSLogUpdateOne) ClearCode() *SMSLogUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetChannel sets the "channel" field.
func (_u *SMSLogUpdateOne) SetChannel(v smslog.Channel) *SMSLogUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableChannel(v *smslog.Channel) *SMSLogUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SMSLogUpdateOne) SetStatus(v smslog.Status) *SMSLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableStatus(v *smslog.Status) *SMSLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SMSLogUpdateOne) SetErrorMessage(v string) *SMSLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableErrorMessage(v *string) *SMSLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SMSLogUpdateOne) ClearErrorMessage() *SMSLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *SMSLogUpdateOne) SetSentAt(v time.Time) *SMSLogUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableSentAt(v *time.Time) *SMSLogUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SMSLogUpdateOne) SetExpiresAt(v time.Time) *SMSLogUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SMSLogUpdateOne) SetNillableExpiresAt(v *time.Time) *SMSLogUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SMSLogUpdateOne) ClearExpiresAt() *SMSLogUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the SMSLogMutation object of the builder.
func (_u *SMSLogUpdateOne) Mutation() *SMSLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the SMSLogUpdate builder.
func (_u *SMSLogUpdateOne) Where(ps ...predicate.SMSLog) *SMSLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SMSLogUpdateOne) Select(field string, fields ...string) *SMSLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SMSLog entity.
func (_u *SMSLogUpdateOne) Save(ctx context.Context) (*SMSLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SMSLogUpdateOne) SaveX(ctx context.Context) *SMSLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SMSLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SMSLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SMSLogUpdateOne) check() error {
	if v, ok := _u.mutation.Phone(); ok {
		if err := smslog.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SMSLog.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SmsType(); ok {
		if err := smslog.SmsTypeValidator(v); err != nil {
			return &ValidationError{Name: "sms_type", err: fmt.Errorf(`ent: validator failed for field "SMSLog.sms_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := smslog.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SMSLog.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := smslog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SMSLog.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := smslog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "SMSLog.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := smslog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SMSLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := smslog.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "SMSLog.error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *SMSLogUpdateOne) sqlSave(ctx context.Context) (_node *SMSLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(smslog.Table, smslog.Columns, sqlgraph.NewFieldSpec(smslog.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SMSLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, smslog.FieldID)
		for _, f := range fields {
			if !smslog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != smslog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(smslog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(smslog.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.SmsType(); ok {
		_spec.SetField(smslog.FieldSmsType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(smslog.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(smslog.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(smslog.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(smslog.FieldChannel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(smslog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(smslog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(smslog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(smslog.FieldSentAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(smslog.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(smslog.FieldExpiresAt, field.TypeTime)
	}
	_node = &SMSLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{smslog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
