// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/tenantconfig"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantConfigCreate is the builder for creating a TenantConfig entity.
type TenantConfigCreate struct {
	config
	mutation *TenantConfigMutation
	hooks    []Hook
}

// SetCreatedBy sets the "created_by" field.
func (_c *TenantConfigCreate) SetCreatedBy(v uint32) *TenantConfigCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableCreatedBy(v *uint32) *TenantConfigCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *TenantConfigCreate) SetUpdatedBy(v uint32) *TenantConfigCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableUpdatedBy(v *uint32) *TenantConfigCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *TenantConfigCreate) SetDeletedBy(v uint32) *TenantConfigCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableDeletedBy(v *uint32) *TenantConfigCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantConfigCreate) SetCreatedAt(v time.Time) *TenantConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableCreatedAt(v *time.Time) *TenantConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantConfigCreate) SetUpdatedAt(v time.Time) *TenantConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableUpdatedAt(v *time.Time) *TenantConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TenantConfigCreate) SetDeletedAt(v time.Time) *TenantConfigCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableDeletedAt(v *time.Time) *TenantConfigCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantConfigCreate) SetTenantID(v uint32) *TenantConfigCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableTenantID(v *uint32) *TenantConfigCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetConfigKey sets the "config_key" field.
func (_c *TenantConfigCreate) SetConfigKey(v string) *TenantConfigCreate {
	_c.mutation.SetConfigKey(v)
	return _c
}

// SetConfigValue sets the "config_value" field.
func (_c *TenantConfigCreate) SetConfigValue(v string) *TenantConfigCreate {
	_c.mutation.SetConfigValue(v)
	return _c
}

// SetNillableConfigValue sets the "config_value" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableConfigValue(v *string) *TenantConfigCreate {
	if v != nil {
		_c.SetConfigValue(*v)
	}
	return _c
}

// SetConfigType sets the "config_type" field.
func (_c *TenantConfigCreate) SetConfigType(v string) *TenantConfigCreate {
	_c.mutation.SetConfigType(v)
	return _c
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableConfigType(v *string) *TenantConfigCreate {
	if v != nil {
		_c.SetConfigType(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *TenantConfigCreate) SetDescription(v string) *TenantConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableDescription(v *string) *TenantConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *TenantConfigCreate) SetCategory(v string) *TenantConfigCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableCategory(v *string) *TenantConfigCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetIsEncrypted sets the "is_encrypted" field.
func (_c *TenantConfigCreate) SetIsEncrypted(v bool) *TenantConfigCreate {
	_c.mutation.SetIsEncrypted(v)
	return _c
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableIsEncrypted(v *bool) *TenantConfigCreate {
	if v != nil {
		_c.SetIsEncrypted(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TenantConfigCreate) SetIsActive(v bool) *TenantConfigCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableIsActive(v *bool) *TenantConfigCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetValidationRule sets the "validation_rule" field.
func (_c *TenantConfigCreate) SetValidationRule(v string) *TenantConfigCreate {
	_c.mutation.SetValidationRule(v)
	return _c
}

// SetNillableValidationRule sets the "validation_rule" field if the given value is not nil.
func (_c *TenantConfigCreate) SetNillableValidationRule(v *string) *TenantConfigCreate {
	if v != nil {
		_c.SetValidationRule(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantConfigCreate) SetID(v uint32) *TenantConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TenantConfigMutation object of the builder.
func (_c *TenantConfigCreate) Mutation() *TenantConfigMutation {
	return _c.mutation
}

// Save creates the TenantConfig in the database.
func (_c *TenantConfigCreate) Save(ctx context.Context) (*TenantConfig, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantConfigCreate) SaveX(ctx context.Context) *TenantConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantConfigCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := tenantconfig.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.ConfigType(); !ok {
		v := tenantconfig.DefaultConfigType
		_c.mutation.SetConfigType(v)
	}
	if _, ok := _c.mutation.IsEncrypted(); !ok {
		v := tenantconfig.DefaultIsEncrypted
		_c.mutation.SetIsEncrypted(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := tenantconfig.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantConfigCreate) check() error {
	if _, ok := _c.mutation.ConfigKey(); !ok {
		return &ValidationError{Name: "config_key", err: errors.New(`ent: missing required field "TenantConfig.config_key"`)}
	}
	if v, ok := _c.mutation.ConfigKey(); ok {
		if err := tenantconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ConfigValue(); ok {
		if err := tenantconfig.ConfigValueValidator(v); err != nil {
			return &ValidationError{Name: "config_value", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConfigType(); !ok {
		return &ValidationError{Name: "config_type", err: errors.New(`ent: missing required field "TenantConfig.config_type"`)}
	}
	if v, ok := _c.mutation.ConfigType(); ok {
		if err := tenantconfig.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := tenantconfig.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := tenantconfig.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEncrypted(); !ok {
		return &ValidationError{Name: "is_encrypted", err: errors.New(`ent: missing required field "TenantConfig.is_encrypted"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "TenantConfig.is_active"`)}
	}
	if v, ok := _c.mutation.ValidationRule(); ok {
		if err := tenantconfig.ValidationRuleValidator(v); err != nil {
			return &ValidationError{Name: "validation_rule", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.validation_rule": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tenantconfig.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TenantConfigCreate) sqlSave(ctx context.Context) (*TenantConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantConfigCreate) createSpec() (*TenantConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantconfig.Table, sqlgraph.NewFieldSpec(tenantconfig.FieldID, field.TypeUint32))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(tenantconfig.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(tenantconfig.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(tenantconfig.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tenantconfig.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ConfigKey(); ok {
		_spec.SetField(tenantconfig.FieldConfigKey, field.TypeString, value)
		_node.ConfigKey = value
	}
	if value, ok := _c.mutation.ConfigValue(); ok {
		_spec.SetField(tenantconfig.FieldConfigValue, field.TypeString, value)
		_node.ConfigValue = &value
	}
	if value, ok := _c.mutation.ConfigType(); ok {
		_spec.SetField(tenantconfig.FieldConfigType, field.TypeString, value)
		_node.ConfigType = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(tenantconfig.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(tenantconfig.FieldCategory, field.TypeString, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.IsEncrypted(); ok {
		_spec.SetField(tenantconfig.FieldIsEncrypted, field.TypeBool, value)
		_node.IsEncrypted = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(tenantconfig.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.ValidationRule(); ok {
		_spec.SetField(tenantconfig.FieldValidationRule, field.TypeString, value)
		_node.ValidationRule = &value
	}
	return _node, _spec
}

// TenantConfigCreateBulk is the builder for creating many TenantConfig entities in bulk.
type TenantConfigCreateBulk struct {
	config
	err      error
	builders []*TenantConfigCreate
}

// Save creates the TenantConfig entities in the database.
func (_c *TenantConfigCreateBulk) Save(ctx context.Context) ([]*TenantConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantConfigCreateBulk) SaveX(ctx context.Context) []*TenantConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
