// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"go-wind-admin/app/consumer/service/internal/data/ent/tenantconfig"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantConfigUpdate is the builder for updating TenantConfig entities.
type TenantConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *TenantConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TenantConfigUpdate builder.
func (_u *TenantConfigUpdate) Where(ps ...predicate.TenantConfig) *TenantConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TenantConfigUpdate) SetCreatedBy(v uint32) *TenantConfigUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableCreatedBy(v *uint32) *TenantConfigUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TenantConfigUpdate) AddCreatedBy(v int32) *TenantConfigUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TenantConfigUpdate) ClearCreatedBy() *TenantConfigUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TenantConfigUpdate) SetUpdatedBy(v uint32) *TenantConfigUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableUpdatedBy(v *uint32) *TenantConfigUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *TenantConfigUpdate) AddUpdatedBy(v int32) *TenantConfigUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TenantConfigUpdate) ClearUpdatedBy() *TenantConfigUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *TenantConfigUpdate) SetDeletedBy(v uint32) *TenantConfigUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableDeletedBy(v *uint32) *TenantConfigUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *TenantConfigUpdate) AddDeletedBy(v int32) *TenantConfigUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *TenantConfigUpdate) ClearDeletedBy() *TenantConfigUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantConfigUpdate) SetUpdatedAt(v time.Time) *TenantConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableUpdatedAt(v *time.Time) *TenantConfigUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TenantConfigUpdate) ClearUpdatedAt() *TenantConfigUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TenantConfigUpdate) SetDeletedAt(v time.Time) *TenantConfigUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableDeletedAt(v *time.Time) *TenantConfigUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TenantConfigUpdate) ClearDeletedAt() *TenantConfigUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetConfigKey sets the "config_key" field.
func (_u *TenantConfigUpdate) SetConfigKey(v string) *TenantConfigUpdate {
	_u.mutation.SetConfigKey(v)
	return _u
}

// SetNillableConfigKey sets the "config_key" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableConfigKey(v *string) *TenantConfigUpdate {
	if v != nil {
		_u.SetConfigKey(*v)
	}
	return _u
}

// SetConfigValue sets the "config_value" field.
func (_u *TenantConfigUpdate) SetConfigValue(v string) *TenantConfigUpdate {
	_u.mutation.SetConfigValue(v)
	return _u
}

// SetNillableConfigValue sets the "config_value" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableConfigValue(v *string) *TenantConfigUpdate {
	if v != nil {
		_u.SetConfigValue(*v)
	}
	return _u
}

// ClearConfigValue clears the value of the "config_value" field.
func (_u *TenantConfigUpdate) ClearConfigValue() *TenantConfigUpdate {
	_u.mutation.ClearConfigValue()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantConfigUpdate) SetDescription(v string) *TenantConfigUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableDescription(v *string) *TenantConfigUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TenantConfigUpdate) ClearDescription() *TenantConfigUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetConfigType sets the "config_type" field.
func (_u *TenantConfigUpdate) SetConfigType(v tenantconfig.ConfigType) *TenantConfigUpdate {
	_u.mutation.SetConfigType(v)
	return _u
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableConfigType(v *tenantconfig.ConfigType) *TenantConfigUpdate {
	if v != nil {
		_u.SetConfigType(*v)
	}
	return _u
}

// SetIsEncrypted sets the "is_encrypted" field.
func (_u *TenantConfigUpdate) SetIsEncrypted(v bool) *TenantConfigUpdate {
	_u.mutation.SetIsEncrypted(v)
	return _u
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableIsEncrypted(v *bool) *TenantConfigUpdate {
	if v != nil {
		_u.SetIsEncrypted(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TenantConfigUpdate) SetIsActive(v bool) *TenantConfigUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TenantConfigUpdate) SetNillableIsActive(v *bool) *TenantConfigUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the TenantConfigMutation object of the builder.
func (_u *TenantConfigUpdate) Mutation() *TenantConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantConfigUpdate) check() error {
	if v, ok := _u.mutation.ConfigKey(); ok {
		if err := tenantconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigValue(); ok {
		if err := tenantconfig.ConfigValueValidator(v); err != nil {
			return &ValidationError{Name: "config_value", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := tenantconfig.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigType(); ok {
		if err := tenantconfig.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantconfig.Table, tenantconfig.Columns, sqlgraph.NewFieldSpec(tenantconfig.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tenantconfig.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tenantconfig.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(tenantconfig.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(tenantconfig.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(tenantconfig.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(tenantconfig.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(tenantconfig.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(tenantconfig.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(tenantconfig.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(tenantconfig.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tenantconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tenantconfig.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(tenantconfig.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConfigKey(); ok {
		_spec.SetField(tenantconfig.FieldConfigKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigValue(); ok {
		_spec.SetField(tenantconfig.FieldConfigValue, field.TypeString, value)
	}
	if _u.mutation.ConfigValueCleared() {
		_spec.ClearField(tenantconfig.FieldConfigValue, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenantconfig.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tenantconfig.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigType(); ok {
		_spec.SetField(tenantconfig.FieldConfigType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsEncrypted(); ok {
		_spec.SetField(tenantconfig.FieldIsEncrypted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(tenantconfig.FieldIsActive, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantConfigUpdateOne is the builder for updating a single TenantConfig entity.
type TenantConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TenantConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedBy sets the "created_by" field.
func (_u *TenantConfigUpdateOne) SetCreatedBy(v uint32) *TenantConfigUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableCreatedBy(v *uint32) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TenantConfigUpdateOne) AddCreatedBy(v int32) *TenantConfigUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TenantConfigUpdateOne) ClearCreatedBy() *TenantConfigUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TenantConfigUpdateOne) SetUpdatedBy(v uint32) *TenantConfigUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableUpdatedBy(v *uint32) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *TenantConfigUpdateOne) AddUpdatedBy(v int32) *TenantConfigUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TenantConfigUpdateOne) ClearUpdatedBy() *TenantConfigUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *TenantConfigUpdateOne) SetDeletedBy(v uint32) *TenantConfigUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableDeletedBy(v *uint32) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *TenantConfigUpdateOne) AddDeletedBy(v int32) *TenantConfigUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *TenantConfigUpdateOne) ClearDeletedBy() *TenantConfigUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantConfigUpdateOne) SetUpdatedAt(v time.Time) *TenantConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableUpdatedAt(v *time.Time) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TenantConfigUpdateOne) ClearUpdatedAt() *TenantConfigUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TenantConfigUpdateOne) SetDeletedAt(v time.Time) *TenantConfigUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableDeletedAt(v *time.Time) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TenantConfigUpdateOne) ClearDeletedAt() *TenantConfigUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetConfigKey sets the "config_key" field.
func (_u *TenantConfigUpdateOne) SetConfigKey(v string) *TenantConfigUpdateOne {
	_u.mutation.SetConfigKey(v)
	return _u
}

// SetNillableConfigKey sets the "config_key" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableConfigKey(v *string) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetConfigKey(*v)
	}
	return _u
}

// SetConfigValue sets the "config_value" field.
func (_u *TenantConfigUpdateOne) SetConfigValue(v string) *TenantConfigUpdateOne {
	_u.mutation.SetConfigValue(v)
	return _u
}

// SetNillableConfigValue sets the "config_value" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableConfigValue(v *string) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetConfigValue(*v)
	}
	return _u
}

// ClearConfigValue clears the value of the "config_value" field.
func (_u *TenantConfigUpdateOne) ClearConfigValue() *TenantConfigUpdateOne {
	_u.mutation.ClearConfigValue()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantConfigUpdateOne) SetDescription(v string) *TenantConfigUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableDescription(v *string) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TenantConfigUpdateOne) ClearDescription() *TenantConfigUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetConfigType sets the "config_type" field.
func (_u *TenantConfigUpdateOne) SetConfigType(v tenantconfig.ConfigType) *TenantConfigUpdateOne {
	_u.mutation.SetConfigType(v)
	return _u
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableConfigType(v *tenantconfig.ConfigType) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetConfigType(*v)
	}
	return _u
}

// SetIsEncrypted sets the "is_encrypted" field.
func (_u *TenantConfigUpdateOne) SetIsEncrypted(v bool) *TenantConfigUpdateOne {
	_u.mutation.SetIsEncrypted(v)
	return _u
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableIsEncrypted(v *bool) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetIsEncrypted(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TenantConfigUpdateOne) SetIsActive(v bool) *TenantConfigUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TenantConfigUpdateOne) SetNillableIsActive(v *bool) *TenantConfigUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the TenantConfigMutation object of the builder.
func (_u *TenantConfigUpdateOne) Mutation() *TenantConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantConfigUpdate builder.
func (_u *TenantConfigUpdateOne) Where(ps ...predicate.TenantConfig) *TenantConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantConfigUpdateOne) Select(field string, fields ...string) *TenantConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantConfig entity.
func (_u *TenantConfigUpdateOne) Save(ctx context.Context) (*TenantConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantConfigUpdateOne) SaveX(ctx context.Context) *TenantConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantConfigUpdateOne) check() error {
	if v, ok := _u.mutation.ConfigKey(); ok {
		if err := tenantconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigValue(); ok {
		if err := tenantconfig.ConfigValueValidator(v); err != nil {
			return &ValidationError{Name: "config_value", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := tenantconfig.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigType(); ok {
		if err := tenantconfig.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "TenantConfig.config_type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantConfigUpdateOne) sqlSave(ctx context.Context) (_node *TenantConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantconfig.Table, tenantconfig.Columns, sqlgraph.NewFieldSpec(tenantconfig.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantconfig.FieldID)
		for _, f := range fields {
			if !tenantconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tenantconfig.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tenantconfig.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(tenantconfig.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(tenantconfig.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(tenantconfig.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(tenantconfig.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(tenantconfig.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(tenantconfig.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(tenantconfig.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(tenantconfig.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tenantconfig.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tenantconfig.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(tenantconfig.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConfigKey(); ok {
		_spec.SetField(tenantconfig.FieldConfigKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigValue(); ok {
		_spec.SetField(tenantconfig.FieldConfigValue, field.TypeString, value)
	}
	if _u.mutation.ConfigValueCleared() {
		_spec.ClearField(tenantconfig.FieldConfigValue, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenantconfig.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tenantconfig.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ConfigType(); ok {
		_spec.SetField(tenantconfig.FieldConfigType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsEncrypted(); ok {
		_spec.SetField(tenantconfig.FieldIsEncrypted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(tenantconfig.FieldIsActive, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TenantConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
