// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"go-wind-admin/app/consumer/service/internal/data/ent/tenantconfighistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantConfigHistoryDelete is the builder for deleting a TenantConfigHistory entity.
type TenantConfigHistoryDelete struct {
	config
	hooks    []Hook
	mutation *TenantConfigHistoryMutation
}

// Where appends a list predicates to the TenantConfigHistoryDelete builder.
func (_d *TenantConfigHistoryDelete) Where(ps ...predicate.TenantConfigHistory) *TenantConfigHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TenantConfigHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantConfigHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TenantConfigHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantconfighistory.Table, sqlgraph.NewFieldSpec(tenantconfighistory.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TenantConfigHistoryDeleteOne is the builder for deleting a single TenantConfigHistory entity.
type TenantConfigHistoryDeleteOne struct {
	_d *TenantConfigHistoryDelete
}

// Where appends a list predicates to the TenantConfigHistoryDelete builder.
func (_d *TenantConfigHistoryDeleteOne) Where(ps ...predicate.TenantConfigHistory) *TenantConfigHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TenantConfigHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantconfighistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantConfigHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
