// Code generated by ent, DO NOT EDIT.

package freighttemplate

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the freighttemplate type in the database.
	Label = "freight_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCalculationType holds the string denoting the calculation_type field in the database.
	FieldCalculationType = "calculation_type"
	// FieldFirstWeight holds the string denoting the first_weight field in the database.
	FieldFirstWeight = "first_weight"
	// FieldFirstPrice holds the string denoting the first_price field in the database.
	FieldFirstPrice = "first_price"
	// FieldAdditionalWeight holds the string denoting the additional_weight field in the database.
	FieldAdditionalWeight = "additional_weight"
	// FieldAdditionalPrice holds the string denoting the additional_price field in the database.
	FieldAdditionalPrice = "additional_price"
	// FieldRegionRules holds the string denoting the region_rules field in the database.
	FieldRegionRules = "region_rules"
	// FieldFreeShippingRules holds the string denoting the free_shipping_rules field in the database.
	FieldFreeShippingRules = "free_shipping_rules"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// Table holds the table name of the freighttemplate in the database.
	Table = "consumer_freight_templates"
)

// Columns holds all SQL columns for freighttemplate fields.
var Columns = []string{
	FieldID,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTenantID,
	FieldName,
	FieldCalculationType,
	FieldFirstWeight,
	FieldFirstPrice,
	FieldAdditionalWeight,
	FieldAdditionalPrice,
	FieldRegionRules,
	FieldFreeShippingRules,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-admin/app/consumer/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// FirstWeightValidator is a validator for the "first_weight" field. It is called by the builders before save.
	FirstWeightValidator func(string) error
	// FirstPriceValidator is a validator for the "first_price" field. It is called by the builders before save.
	FirstPriceValidator func(string) error
	// AdditionalWeightValidator is a validator for the "additional_weight" field. It is called by the builders before save.
	AdditionalWeightValidator func(string) error
	// AdditionalPriceValidator is a validator for the "additional_price" field. It is called by the builders before save.
	AdditionalPriceValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// CalculationType defines the type for the "calculation_type" enum field.
type CalculationType string

// CalculationType values.
const (
	CalculationTypeByWeight   CalculationType = "BY_WEIGHT"
	CalculationTypeByDistance CalculationType = "BY_DISTANCE"
)

func (ct CalculationType) String() string {
	return string(ct)
}

// CalculationTypeValidator is a validator for the "calculation_type" field enum values. It is called by the builders before save.
func CalculationTypeValidator(ct CalculationType) error {
	switch ct {
	case CalculationTypeByWeight, CalculationTypeByDistance:
		return nil
	default:
		return fmt.Errorf("freighttemplate: invalid enum value for calculation_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the FreightTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCalculationType orders the results by the calculation_type field.
func ByCalculationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalculationType, opts...).ToFunc()
}

// ByFirstWeight orders the results by the first_weight field.
func ByFirstWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstWeight, opts...).ToFunc()
}

// ByFirstPrice orders the results by the first_price field.
func ByFirstPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstPrice, opts...).ToFunc()
}

// ByAdditionalWeight orders the results by the additional_weight field.
func ByAdditionalWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdditionalWeight, opts...).ToFunc()
}

// ByAdditionalPrice orders the results by the additional_price field.
func ByAdditionalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdditionalPrice, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}
