// Code generated by ent, DO NOT EDIT.

package tenantconfighistory

import (
	"go-wind-admin/app/consumer/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldTenantID, v))
}

// ConfigID applies equality check predicate on the "config_id" field. It's identical to ConfigIDEQ.
func ConfigID(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldConfigID, v))
}

// ConfigKey applies equality check predicate on the "config_key" field. It's identical to ConfigKeyEQ.
func ConfigKey(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldConfigKey, v))
}

// OldValue applies equality check predicate on the "old_value" field. It's identical to OldValueEQ.
func OldValue(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldOldValue, v))
}

// NewValue applies equality check predicate on the "new_value" field. It's identical to NewValueEQ.
func NewValue(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldNewValue, v))
}

// ChangeReason applies equality check predicate on the "change_reason" field. It's identical to ChangeReasonEQ.
func ChangeReason(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangeReason, v))
}

// ChangedBy applies equality check predicate on the "changed_by" field. It's identical to ChangedByEQ.
func ChangedBy(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByName applies equality check predicate on the "changed_by_name" field. It's identical to ChangedByNameEQ.
func ChangedByName(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangedByName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldDeletedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldTenantID))
}

// ConfigIDEQ applies the EQ predicate on the "config_id" field.
func ConfigIDEQ(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldConfigID, v))
}

// ConfigIDNEQ applies the NEQ predicate on the "config_id" field.
func ConfigIDNEQ(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldConfigID, v))
}

// ConfigIDIn applies the In predicate on the "config_id" field.
func ConfigIDIn(vs ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldConfigID, vs...))
}

// ConfigIDNotIn applies the NotIn predicate on the "config_id" field.
func ConfigIDNotIn(vs ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldConfigID, vs...))
}

// ConfigIDGT applies the GT predicate on the "config_id" field.
func ConfigIDGT(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldConfigID, v))
}

// ConfigIDGTE applies the GTE predicate on the "config_id" field.
func ConfigIDGTE(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldConfigID, v))
}

// ConfigIDLT applies the LT predicate on the "config_id" field.
func ConfigIDLT(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldConfigID, v))
}

// ConfigIDLTE applies the LTE predicate on the "config_id" field.
func ConfigIDLTE(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldConfigID, v))
}

// ConfigKeyEQ applies the EQ predicate on the "config_key" field.
func ConfigKeyEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigKeyNEQ applies the NEQ predicate on the "config_key" field.
func ConfigKeyNEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldConfigKey, v))
}

// ConfigKeyIn applies the In predicate on the "config_key" field.
func ConfigKeyIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldConfigKey, vs...))
}

// ConfigKeyNotIn applies the NotIn predicate on the "config_key" field.
func ConfigKeyNotIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldConfigKey, vs...))
}

// ConfigKeyGT applies the GT predicate on the "config_key" field.
func ConfigKeyGT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldConfigKey, v))
}

// ConfigKeyGTE applies the GTE predicate on the "config_key" field.
func ConfigKeyGTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldConfigKey, v))
}

// ConfigKeyLT applies the LT predicate on the "config_key" field.
func ConfigKeyLT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldConfigKey, v))
}

// ConfigKeyLTE applies the LTE predicate on the "config_key" field.
func ConfigKeyLTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldConfigKey, v))
}

// ConfigKeyContains applies the Contains predicate on the "config_key" field.
func ConfigKeyContains(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContains(FieldConfigKey, v))
}

// ConfigKeyHasPrefix applies the HasPrefix predicate on the "config_key" field.
func ConfigKeyHasPrefix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasPrefix(FieldConfigKey, v))
}

// ConfigKeyHasSuffix applies the HasSuffix predicate on the "config_key" field.
func ConfigKeyHasSuffix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasSuffix(FieldConfigKey, v))
}

// ConfigKeyEqualFold applies the EqualFold predicate on the "config_key" field.
func ConfigKeyEqualFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEqualFold(FieldConfigKey, v))
}

// ConfigKeyContainsFold applies the ContainsFold predicate on the "config_key" field.
func ConfigKeyContainsFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContainsFold(FieldConfigKey, v))
}

// OldValueEQ applies the EQ predicate on the "old_value" field.
func OldValueEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldOldValue, v))
}

// OldValueNEQ applies the NEQ predicate on the "old_value" field.
func OldValueNEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldOldValue, v))
}

// OldValueIn applies the In predicate on the "old_value" field.
func OldValueIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldOldValue, vs...))
}

// OldValueNotIn applies the NotIn predicate on the "old_value" field.
func OldValueNotIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldOldValue, vs...))
}

// OldValueGT applies the GT predicate on the "old_value" field.
func OldValueGT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldOldValue, v))
}

// OldValueGTE applies the GTE predicate on the "old_value" field.
func OldValueGTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldOldValue, v))
}

// OldValueLT applies the LT predicate on the "old_value" field.
func OldValueLT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldOldValue, v))
}

// OldValueLTE applies the LTE predicate on the "old_value" field.
func OldValueLTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldOldValue, v))
}

// OldValueContains applies the Contains predicate on the "old_value" field.
func OldValueContains(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContains(FieldOldValue, v))
}

// OldValueHasPrefix applies the HasPrefix predicate on the "old_value" field.
func OldValueHasPrefix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasPrefix(FieldOldValue, v))
}

// OldValueHasSuffix applies the HasSuffix predicate on the "old_value" field.
func OldValueHasSuffix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasSuffix(FieldOldValue, v))
}

// OldValueIsNil applies the IsNil predicate on the "old_value" field.
func OldValueIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldOldValue))
}

// OldValueNotNil applies the NotNil predicate on the "old_value" field.
func OldValueNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldOldValue))
}

// OldValueEqualFold applies the EqualFold predicate on the "old_value" field.
func OldValueEqualFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEqualFold(FieldOldValue, v))
}

// OldValueContainsFold applies the ContainsFold predicate on the "old_value" field.
func OldValueContainsFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContainsFold(FieldOldValue, v))
}

// NewValueEQ applies the EQ predicate on the "new_value" field.
func NewValueEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldNewValue, v))
}

// NewValueNEQ applies the NEQ predicate on the "new_value" field.
func NewValueNEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldNewValue, v))
}

// NewValueIn applies the In predicate on the "new_value" field.
func NewValueIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldNewValue, vs...))
}

// NewValueNotIn applies the NotIn predicate on the "new_value" field.
func NewValueNotIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldNewValue, vs...))
}

// NewValueGT applies the GT predicate on the "new_value" field.
func NewValueGT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldNewValue, v))
}

// NewValueGTE applies the GTE predicate on the "new_value" field.
func NewValueGTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldNewValue, v))
}

// NewValueLT applies the LT predicate on the "new_value" field.
func NewValueLT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldNewValue, v))
}

// NewValueLTE applies the LTE predicate on the "new_value" field.
func NewValueLTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldNewValue, v))
}

// NewValueContains applies the Contains predicate on the "new_value" field.
func NewValueContains(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContains(FieldNewValue, v))
}

// NewValueHasPrefix applies the HasPrefix predicate on the "new_value" field.
func NewValueHasPrefix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasPrefix(FieldNewValue, v))
}

// NewValueHasSuffix applies the HasSuffix predicate on the "new_value" field.
func NewValueHasSuffix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasSuffix(FieldNewValue, v))
}

// NewValueIsNil applies the IsNil predicate on the "new_value" field.
func NewValueIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldNewValue))
}

// NewValueNotNil applies the NotNil predicate on the "new_value" field.
func NewValueNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldNewValue))
}

// NewValueEqualFold applies the EqualFold predicate on the "new_value" field.
func NewValueEqualFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEqualFold(FieldNewValue, v))
}

// NewValueContainsFold applies the ContainsFold predicate on the "new_value" field.
func NewValueContainsFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContainsFold(FieldNewValue, v))
}

// ChangeTypeEQ applies the EQ predicate on the "change_type" field.
func ChangeTypeEQ(v ChangeType) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangeType, v))
}

// ChangeTypeNEQ applies the NEQ predicate on the "change_type" field.
func ChangeTypeNEQ(v ChangeType) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldChangeType, v))
}

// ChangeTypeIn applies the In predicate on the "change_type" field.
func ChangeTypeIn(vs ...ChangeType) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldChangeType, vs...))
}

// ChangeTypeNotIn applies the NotIn predicate on the "change_type" field.
func ChangeTypeNotIn(vs ...ChangeType) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldChangeType, vs...))
}

// ChangeReasonEQ applies the EQ predicate on the "change_reason" field.
func ChangeReasonEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangeReason, v))
}

// ChangeReasonNEQ applies the NEQ predicate on the "change_reason" field.
func ChangeReasonNEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldChangeReason, v))
}

// ChangeReasonIn applies the In predicate on the "change_reason" field.
func ChangeReasonIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldChangeReason, vs...))
}

// ChangeReasonNotIn applies the NotIn predicate on the "change_reason" field.
func ChangeReasonNotIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldChangeReason, vs...))
}

// ChangeReasonGT applies the GT predicate on the "change_reason" field.
func ChangeReasonGT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldChangeReason, v))
}

// ChangeReasonGTE applies the GTE predicate on the "change_reason" field.
func ChangeReasonGTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldChangeReason, v))
}

// ChangeReasonLT applies the LT predicate on the "change_reason" field.
func ChangeReasonLT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldChangeReason, v))
}

// ChangeReasonLTE applies the LTE predicate on the "change_reason" field.
func ChangeReasonLTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldChangeReason, v))
}

// ChangeReasonContains applies the Contains predicate on the "change_reason" field.
func ChangeReasonContains(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContains(FieldChangeReason, v))
}

// ChangeReasonHasPrefix applies the HasPrefix predicate on the "change_reason" field.
func ChangeReasonHasPrefix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasPrefix(FieldChangeReason, v))
}

// ChangeReasonHasSuffix applies the HasSuffix predicate on the "change_reason" field.
func ChangeReasonHasSuffix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasSuffix(FieldChangeReason, v))
}

// ChangeReasonIsNil applies the IsNil predicate on the "change_reason" field.
func ChangeReasonIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldChangeReason))
}

// ChangeReasonNotNil applies the NotNil predicate on the "change_reason" field.
func ChangeReasonNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldChangeReason))
}

// ChangeReasonEqualFold applies the EqualFold predicate on the "change_reason" field.
func ChangeReasonEqualFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEqualFold(FieldChangeReason, v))
}

// ChangeReasonContainsFold applies the ContainsFold predicate on the "change_reason" field.
func ChangeReasonContainsFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContainsFold(FieldChangeReason, v))
}

// ChangedByEQ applies the EQ predicate on the "changed_by" field.
func ChangedByEQ(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByNEQ applies the NEQ predicate on the "changed_by" field.
func ChangedByNEQ(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldChangedBy, v))
}

// ChangedByIn applies the In predicate on the "changed_by" field.
func ChangedByIn(vs ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldChangedBy, vs...))
}

// ChangedByNotIn applies the NotIn predicate on the "changed_by" field.
func ChangedByNotIn(vs ...uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldChangedBy, vs...))
}

// ChangedByGT applies the GT predicate on the "changed_by" field.
func ChangedByGT(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldChangedBy, v))
}

// ChangedByGTE applies the GTE predicate on the "changed_by" field.
func ChangedByGTE(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldChangedBy, v))
}

// ChangedByLT applies the LT predicate on the "changed_by" field.
func ChangedByLT(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldChangedBy, v))
}

// ChangedByLTE applies the LTE predicate on the "changed_by" field.
func ChangedByLTE(v uint32) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldChangedBy, v))
}

// ChangedByNameEQ applies the EQ predicate on the "changed_by_name" field.
func ChangedByNameEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEQ(FieldChangedByName, v))
}

// ChangedByNameNEQ applies the NEQ predicate on the "changed_by_name" field.
func ChangedByNameNEQ(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNEQ(FieldChangedByName, v))
}

// ChangedByNameIn applies the In predicate on the "changed_by_name" field.
func ChangedByNameIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIn(FieldChangedByName, vs...))
}

// ChangedByNameNotIn applies the NotIn predicate on the "changed_by_name" field.
func ChangedByNameNotIn(vs ...string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotIn(FieldChangedByName, vs...))
}

// ChangedByNameGT applies the GT predicate on the "changed_by_name" field.
func ChangedByNameGT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGT(FieldChangedByName, v))
}

// ChangedByNameGTE applies the GTE predicate on the "changed_by_name" field.
func ChangedByNameGTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldGTE(FieldChangedByName, v))
}

// ChangedByNameLT applies the LT predicate on the "changed_by_name" field.
func ChangedByNameLT(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLT(FieldChangedByName, v))
}

// ChangedByNameLTE applies the LTE predicate on the "changed_by_name" field.
func ChangedByNameLTE(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldLTE(FieldChangedByName, v))
}

// ChangedByNameContains applies the Contains predicate on the "changed_by_name" field.
func ChangedByNameContains(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContains(FieldChangedByName, v))
}

// ChangedByNameHasPrefix applies the HasPrefix predicate on the "changed_by_name" field.
func ChangedByNameHasPrefix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasPrefix(FieldChangedByName, v))
}

// ChangedByNameHasSuffix applies the HasSuffix predicate on the "changed_by_name" field.
func ChangedByNameHasSuffix(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldHasSuffix(FieldChangedByName, v))
}

// ChangedByNameIsNil applies the IsNil predicate on the "changed_by_name" field.
func ChangedByNameIsNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldIsNull(FieldChangedByName))
}

// ChangedByNameNotNil applies the NotNil predicate on the "changed_by_name" field.
func ChangedByNameNotNil() predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldNotNull(FieldChangedByName))
}

// ChangedByNameEqualFold applies the EqualFold predicate on the "changed_by_name" field.
func ChangedByNameEqualFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldEqualFold(FieldChangedByName, v))
}

// ChangedByNameContainsFold applies the ContainsFold predicate on the "changed_by_name" field.
func ChangedByNameContainsFold(v string) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.FieldContainsFold(FieldChangedByName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantConfigHistory) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantConfigHistory) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantConfigHistory) predicate.TenantConfigHistory {
	return predicate.TenantConfigHistory(sql.NotPredicates(p))
}
