// Code generated by ent, DO NOT EDIT.

package tenantconfig

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tenantconfig type in the database.
	Label = "tenant_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldConfigKey holds the string denoting the config_key field in the database.
	FieldConfigKey = "config_key"
	// FieldConfigValue holds the string denoting the config_value field in the database.
	FieldConfigValue = "config_value"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldConfigType holds the string denoting the config_type field in the database.
	FieldConfigType = "config_type"
	// FieldIsEncrypted holds the string denoting the is_encrypted field in the database.
	FieldIsEncrypted = "is_encrypted"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// Table holds the table name of the tenantconfig in the database.
	Table = "consumer_tenant_configs"
)

// Columns holds all SQL columns for tenantconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTenantID,
	FieldConfigKey,
	FieldConfigValue,
	FieldDescription,
	FieldConfigType,
	FieldIsEncrypted,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-admin/app/consumer/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// ConfigKeyValidator is a validator for the "config_key" field. It is called by the builders before save.
	ConfigKeyValidator func(string) error
	// ConfigValueValidator is a validator for the "config_value" field. It is called by the builders before save.
	ConfigValueValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultIsEncrypted holds the default value on creation for the "is_encrypted" field.
	DefaultIsEncrypted bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// ConfigType defines the type for the "config_type" enum field.
type ConfigType string

// ConfigTypeSystem is the default value of the ConfigType enum.
const DefaultConfigType = ConfigTypeSystem

// ConfigType values.
const (
	ConfigTypeSMS       ConfigType = "SMS"
	ConfigTypePayment   ConfigType = "PAYMENT"
	ConfigTypeOSS       ConfigType = "OSS"
	ConfigTypeWechat    ConfigType = "WECHAT"
	ConfigTypeLogistics ConfigType = "LOGISTICS"
	ConfigTypeFreight   ConfigType = "FREIGHT"
	ConfigTypeSystem    ConfigType = "SYSTEM"
)

func (ct ConfigType) String() string {
	return string(ct)
}

// ConfigTypeValidator is a validator for the "config_type" field enum values. It is called by the builders before save.
func ConfigTypeValidator(ct ConfigType) error {
	switch ct {
	case ConfigTypeSMS, ConfigTypePayment, ConfigTypeOSS, ConfigTypeWechat, ConfigTypeLogistics, ConfigTypeFreight, ConfigTypeSystem:
		return nil
	default:
		return fmt.Errorf("tenantconfig: invalid enum value for config_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the TenantConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByConfigKey orders the results by the config_key field.
func ByConfigKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigKey, opts...).ToFunc()
}

// ByConfigValue orders the results by the config_value field.
func ByConfigValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigValue, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByConfigType orders the results by the config_type field.
func ByConfigType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigType, opts...).ToFunc()
}

// ByIsEncrypted orders the results by the is_encrypted field.
func ByIsEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEncrypted, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}
